### ISSUE TITLE
Enhancement: Webpack-Config should allow Webfonts

### ISSUE THREAD

**Issue by weblogixx** [newtriks/generator-react-webpack#100]
Hi,

another little thing that I ran into when using your (aweseome) generator: Webfonts (WOFF and WOFF2) are currently not supported by the url-loader plugin configuration.

This could be easily fixed by adjusting the webpack configuration like this:

```javascript
{
  test: /\.(png|jpg|woff|woff2)$/,
  loader: 'url-loader?limit=8192'
}
```

Any chance to see this in a future release?

**Comment by newtriks** [comment]
@weblogixx done my man!

**Comment by weblogixx** [comment]
@newtriks: Now thats a really fast response! Thank you very much :).

**Comment by weblogixx** [comment]
@newtriks: There is one part missing in the unit tests (they do not accept the woff stuff in the webpack config).

```javascript
// In the loaders section:
, {
    test: /\.woff/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff'
  }, {
    test: /\.woff2/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff2'
},
```
Next time ill send a pull request, I swear :).

**Comment by newtriks** [comment]
Done!

> Next time ill send a pull request, I swear :). 

... promises promises :stuck_out_tongue:

> Now thats a really fast response! Thank you very much :).

![giphy](https://cloud.githubusercontent.com/assets/31971/7490888/24dc7e88-f3dc-11e4-9696-a1825d582379.gif)
