### ISSUE TITLE
Add Jest test framework

### ISSUE THREAD

**Issue by gios** [newtriks/generator-react-webpack#102]
Please, add support of [Jest](https://facebook.github.io/jest/). It's more compatible with React.

**Comment by newtriks** [comment]
@gios thanks for the comment, could you list the compatibility advantages over the current setup? Hacks like this still turn me off for using with Webpack: http://stackoverflow.com/questions/28870296/how-to-use-jest-with-webpack. If you wanna add as an additional option and send a pull request that would be appreciated > https://github.com/newtriks/generator-react-webpack/issues/27.
