### ISSUE TITLE
Recommended way to add 3rd party plugins, styles, etc?

### ISSUE THREAD

**Issue by cheeselover** [newtriks/generator-react-webpack#104]
I'm trying to add bootstrap and other 3rd party javascript and css assets into the project.  What is the best way to include them?  I tried bower but I'm not sure how to include them in the webpack build process.

**Comment by weblogixx** [comment]
@cheeselover: You can require css, less or other js files just as shown in the generated components.

For example, you could include Bootstrap like this:

```javascript
// First install bootstrap via npm:
npm install --save bootstrap
npm install --save jquery

// Then, in one of your components (or whereever):
require('bootstrap/dist/css/bootstrap.css');
var jq = require('jquery');
```

As far as I know the files are automatically searched for in the current directory, then in the node_modules folder where they can be found after installing them via npm.

Hope this helps
