### ISSUE TITLE
Use ES6-Classes for React-Components

### ISSUE THREAD

**Issue by weblogixx** [newtriks/generator-react-webpack#106]
As stated in the release post of React v0.13 https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html), React.createClass will get phased out for class usage. As the generator parses ES6 fine, it should be thought about to alter the component skeleton to the new syntax.

Curent output:
```javascript
var Comp = React.createClass({
  render: function () {
    ...........
  }
});

module.exports = Comp;
```

Current working output, without refactoring:
```javascript
var Comp = React.createClass({
  // This shorthand already works
  render() {
    ...........
  }
});

module.exports = Comp;
```

Expected new output:
```javascript
class Comp extends React.Component
  constructor(props) {
    super(props);
    this.state = {};
  },
  render() {
    ...........
  }
});

module.exports = Comp;
```

There are some things to think about before including this feature (like would it be optional, can it be integrated without altering the default configurations too much, ...).

@newtriks: Whats your opinion on this?

**Comment by newtriks** [comment]
@weblogixx really really trying to find the time to do more here but absolutely slammed with work. I agree this is a good discussion to start get going mate thanks.

**Comment by weblogixx** [comment]
@newtriks: Thanks for your feedback. I fully understand that problem (if you can call this a problem when you are a freelancer :)). If you want I could create a branch for this feature.

The question how we want this to be integrated:
- Are there any dependencies on React 0.12.x in the dependency list? Maybe we had to upgrade those too (Did so in my local project and had no problems with 0.13.x so far).
- Should it be the default when generating new components or would it be an option to only use it with the --es6 flag that already exists?
- How should Reflux be handled? I did not work with it, but it seems it is currently only available as a mixin?
- Are there any other gotchas (React Router, Flux?) that may cause problems with this?

**Comment by weblogixx** [comment]
Available as a preview in **v1** branch.
