### ISSUE TITLE
Chrome React extension does not show-up with React Webpack Generator

### ISSUE THREAD

**Issue by remimarenco** [newtriks/generator-react-webpack#109]
Hi!

Thanks for this awesome Generator, it helped me a lot ;).

I began to work on my React project a few weeks ago, and saw a [React dev tool for Chrome](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) has been made...and I wanted to used it!

It did not work, but I guessed it was part of my personal configuration and did go deep further...
BUT

I visited a website where this extension did activate!

I looked into the characteristics and my first guess is that the extension does not look into the iframe where the React root component is injected...

If you know the solution to get things to work properly, that would be awesome!

**Comment by weblogixx** [comment]
@remimarenco Hi, this problem was solved like a month ago (see https://github.com/newtriks/generator-react-webpack/commit/715a0565c2bf726710cf4b9fb17ab01fffa90e8d). Please update the generator to the latest version and add the highlighted lines in the commit to your index.html, it should work then.

**Comment by remimarenco** [comment]
Thank you! It works like a charm ;)
