### ISSUE TITLE
Webpack default settings don't support HTML5 history API

### ISSUE THREAD

**Issue by MickCoelho** [newtriks/generator-react-webpack#117]
Might be better to get it enabled by default into the gruntfile.js 
```
    'webpack-dev-server': {
      options: {
        hot: true,
        port: 8000,
        webpack: webpackDevConfig,
        publicPath: '/assets/',
        contentBase: './<%= pkg.src %>/',
        historyApiFallback: true 
      },
      start: {
        keepAlive: true
      }
    }
```

**Comment by weblogixx** [comment]
@MickCoelho As I dont know this options value: What would be the benefit of enabling it per default? If there is one I will happily add the option.

**Comment by MickCoelho** [comment]
Bit of an old one, so I'm not sure anymore ^_^
I guess enabling that by default will allow you to refresh the page on a specific route without having a 404. React does get the right route when you update the url, but if you refresh the page, the server won't display it (unless you set that value to `true`).

No big deal though, but it might be useful to set it to `true` by default :)

**Comment by weblogixx** [comment]
@MickCoelho: Seems good, will be included in one of the next releases.

**Comment by MickCoelho** [comment]
Nice one!
