### ISSUE TITLE
error test on newly created component

### ISSUE THREAD

**Issue by ferry77** [newtriks/generator-react-webpack#118]
Hi,
I just generate using "yo react-webpack" 
then create component using "yo react-webpack:c ArticleItem --rich"
then run "grunt test" and it produces error as below

ERROR in ./~/css-loader!./~/sass-loader?outputStyle=expanded!./src/styles/ArticleItem.sass
Module build failed: 
.ArticleItem
^
      Invalid top-level expression

Could you please help? Thanks

**Comment by weblogixx** [comment]
@ferry77: Could you please tell me which version of the Generator you are using? I cannot recreate it.

**Comment by ferry77** [comment]
@weblogixx i use generator-react-webpack@1.2.8

**Comment by newtriks** [comment]
@ferry77 could you try using the latest version (currently 1.2.10) and see if it's still reproducable?

**Comment by bsodmike** [comment]
Hey @newtriks I just tried this today with `generator-react-webpack@1.2.11` and still getting that error on running tests,

```
ERROR in ./~/css-loader!./~/sass-loader?outputStyle=expanded!./src/styles/Imagebox.sass
Module build failed:
.Imagebox
^
      Invalid top-level expression
      in /Volumes/foo/hack/node/react-webpack-example/src/styles/Imagebox.sass (line 1, column 1)
 @ ./src/styles/Imagebox.sass 4:14-298
INFO [karma]: Karma v0.12.37 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket VvzYKnxwnjInFmolV93m with id 20249201
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "!!/Volumes/foo/hack/node/react-webpack-example/node_modules/css-loader/index.js!/Volumes/foo/hack/node/react-webpack-example/node_modules/sass-loader/index.js?outputStyle=expanded!/Volumes/foo/hack/node/react-webpack-example/src/styles/Imagebox.sass"
  at /Volumes/foo/hack/node/react-webpack-example/test/spec/components/Imagebox.js:22690
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.075 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.
```

**Comment by weblogixx** [comment]
This error seems to have to do with the automatically generated classNames. It is no longer there in version 2.0 and above. As we do not plan to support the older 1.x branch anymore, I will close this for now.
