### ISSUE TITLE
Update `yeoman-generator`

### ISSUE THREAD

**Issue by arthurvr** [newtriks/generator-react-webpack#119]
Let's update the `yeoman-generator` version the generator is on and [fix all incompatibilities](https://github.com/yeoman/generator/releases).

**Comment by newtriks** [comment]
Great idea @arthurvr, wanna send me a pull request for this?

**Comment by weblogixx** [comment]
@arthurvr This change was done yesterday in our attempt to update the generator. It will be available when the new, slimmed down version can be used as a base for new stable release. Unfortunately, this will take some time.

If you depend on new features in the generator (for whatever reason), you could use my last pull request as a base to include it. Please see https://github.com/weblogixx/generator-react-webpack/commit/5496cac905308166f98d79eae205bf249ee60647)

Closing this for now (as it is coming anyway).

**Comment by arthurvr** [comment]
Thanks! :)
