### ISSUE TITLE
incompatible with react-bootstrap

### ISSUE THREAD

**Issue by ezeql** [newtriks/generator-react-webpack#120]
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDepend
encies requirements!
npm ERR! peerinvalid Peer react-router@0.11.6 wants react@0.12.x
npm ERR! peerinvalid Peer react-bootstrap@0.23.5 wants react@>=0.13
npm ERR! peerinvalid Peer react-hot-loader@1.2.7 wants react@>=0.11.0

**Comment by ezeql** [comment]
setting 
"react-router":"^0.13.0 "
"react": "^0.13.0" 
fixes it.

**Comment by weblogixx** [comment]
I already have this as a pull request, but it is not merged yet...

**Comment by ezeql** [comment]
@weblogixx ok, cool. Thanks.

**Comment by newtriks** [comment]
Should be fixed with #115
