### ISSUE TITLE
Grunt Build barfs on JSX

### ISSUE THREAD

**Issue by epmatsw** [newtriks/generator-react-webpack#121]
Using the following steps generates a non-building project, which seems strange based on the documentation.

`yo react-webpack`
No router, no flux, CSS, JSX
`yo react-webpack:component Tester --rich`
Open `src/components/Bblcc3App.js` and add `var tester = require('./Tester.jsx')`.
`grunt build`

This fails with:
```
ERROR in ./src/components/Tester.jsx
Module parse failed: /Users/will/github/Mine-Temp/BBLCC3/node_modules/eslint-loader/index.js!/Users/will/github/Mine-Temp/BBLCC3/src/components/Tester.jsx Line 20: Unexpected token <
You may need an appropriate loader to handle this file type.
|   render: function () {
|     return (
|         <div className="Tester">
|           <p>Content for Tester</p>
|         </div>
 @ ./src/components/Bblcc3App.js 12:13-36
Warning: Task "webpack:dist" failed. Use --force to continue.
```

**Comment by weblogixx** [comment]
@epmatsw: The webpack dist was not updated correctly. Thank you for reporting this error, should be fixed in no time :).

**Comment by epmatsw** [comment]
Wow! Thanks for the quick fix, was not expecting such a fast turnaround.
