### ISSUE TITLE
generator-react-webpack don't support to build the 3th component based reactjs

### ISSUE THREAD

**Issue by kidyfirst** [newtriks/generator-react-webpack#125]
In my project, i used an other team's reactjs components in my components, but when i build project, it throw

ERROR in ./~/mad-ui-richinput/src/components/RichInput.js
Module parse failed: F:\src\tencentGit\react-demo\node_modules\mad-ui-richinput\src\components\RichInput.js Line 87: Unexpected token <
You may need an appropriate loader to handle this file type.
|         var className = "richinput-wrap "+ this.props.class;
|         return (
|                 <input pattern = {this.props.pattern}
|                        type = "text" ref = "userInput"
 @ ./src/components/MadDemoApp.js 5:16-43

generator-react-webpack don't support to build denpendenced react source component?

**Comment by weblogixx** [comment]
It should work well in any case. Which version are you using? Also, what plugin are you trying to include? Can you please show the complete code of your example? Thank you.

**Comment by kidyfirst** [comment]
the issue can be reproduced when i use the http://instructure-react.github.io/react-menu/ in my project by  var Menu = require('react-menu') ,  it because the module including JSX, and webpack don't compile the node_modules folder.


i must to add follow configuration, my version 1.10.1


var loader_include = [
  path.resolve(__dirname, 'node_modules','react-menu')
};


{
 test: /\.(js|jsx)$/,
 include: loader_include,
 loader: 'react-hot!babel-loader?stage=1'
}









--

QQ:383466933

At 2015-08-25 04:32:55, "Chris" <notifications@github.com> wrote:


It should work well in any case. Which version are you using? Also, what plugin are you trying to include? Can you please show the complete code of your example? Thank you.

**Comment by weblogixx** [comment]
I fully understand your problem. Unfortunately, when using webpack there is kind of a tradeoff between speed (not including node_modules) and compatibility (including it). Currently we do not include it because it runs much faster then.

Maybe we could make this configurable in a later version if more users want to use it like this.
