### ISSUE TITLE
Add redux support

### ISSUE THREAD

**Issue by lcjnil** [newtriks/generator-react-webpack#128]
[Redux](https://github.com/gaearon/redux) seems to be a better Flux implement, hope you could add it.

**Comment by newtriks** [comment]
I'm unsure about this, @lcjnil I regret merging in Flux in the first place to be honest it should have been a seperate generator completely.

**Comment by weblogixx** [comment]
@lcjnil We are currently in a phase of refactoring. We will remove all flux options from the base of the generator. This does __not__ mean that flux will disappear forever here. We will add back support via yeoman compositions (as seen at https://github.com/newtriks/generator-react-webpack/issues/130)

**Comment by lcjnil** [comment]
@weblogixx great thanks for your news, and it's a good idea. I hope I could do some help if possible :)
