### ISSUE TITLE
 Unexpected console statement  no-console

### ISSUE THREAD

**Issue by HelloYie** [newtriks/generator-react-webpack#140]
Cant not use console.log( ) ? How can i debug the code ?

**Comment by chezhe** [comment]
How did you fix it?

**Comment by weblogixx** [comment]
Hi @chezhe,

you may do it by configuring the projects .eslintrc file. Just remove the line ```"no-console": 1,``` or set it to ```"no-console": 0,``` to disable these checks globally. If you want to disable it in one file only, add the following comment on the top of the file:

```javascript
/* eslint no-console: 0*/
```

Hope this helps.

**Comment by chezhe** [comment]
Thanks a lot

**Comment by anssobhi** [comment]
thanks you for this information

**Comment by T1724416608** [comment]
You may do it by replace `console.log` with `window.console.log`

**Comment by ghost** [comment]
> You may do it by replace `console.log` with `window.console.log`

This is a prefect solution for me, thanks!

**Comment by leecin** [comment]
yeah, it's actually `window.console.log`, but why it will be?
