### ISSUE TITLE
"cannot get /" error with react-router

### ISSUE THREAD

**Issue by highlabs** [newtriks/generator-react-webpack#141]
Hi! :)

I started a new project today, and when I tried to create routes like this:
```
//main.js file
var Routes = (
  <Route path="/" handler={App}>
    <Route path="/profile" name="profile" handler={Profile}/>
    <DefaultRoute name="home" handler={Home}/>
  </Route>
);

//app-name.js file

  render: function() {
    return (
      <div className="wrapper">
        <ReactTransitionGroup transitionName="fade">
          <RouteHandler/>
        </ReactTransitionGroup>
      </div>
    );
  }
```

Return "cannot get /profile" error when I access the URL. But DefaultRoute works fine (even when I change {Home} do {Profile}).
What I'm doing wrong? :(

Edit:
It's maybe related to this https://github.com/newtriks/generator-react-webpack/issues/117

I added 'historyApiFallback: true' line in gruntfile.js.
Now I can change url, but they show only '{Home}' content. :/

(If I build the app and run in http serve, works fine)

**Comment by weblogixx** [comment]
Do you have Html5 History support enabled in your router? If not, the url should be something like /#/profile. You can try it if you just include a <Link to="/profile">Test</Link> to one of your components. The url is different when this is not configured.

**Comment by weblogixx** [comment]
Nothing new in 1 month. Closing this for now. If you still have an error with this, please feel free to open another issue.

**Comment by muraveill** [comment]
I have the same issue and I don't really understand your answer. When defining a new Route that has a path different from '/', say '/login', 
- the URL "..../login" returns "cannot get /login"
- the URL "..../#/login" renders the main page instead (same content as '/', without redirection).
I know it is related to using HistoryLocation versus HashLocation in the react-router config, but I did not manage to get it work.

**Comment by weblogixx** [comment]
@muraveill:

A simple example (that is currently working for me) could be:

```javascript
// main.app
'use strict';

var React = require('react/addons');
var Router = require('react-router');
var Route = Router.Route;

// List of components
var FrontendApp = require('./FrontendApp');
var IndexPage = require('./pages/Index');
var HelpPage = require('./pages/Help');

var Routes = (
  <Route handler={FrontendApp} path="/">
    <Route name="/" handler={IndexPage}/>
    <Route name="help" handler={HelpPage}/>
  </Route>
);

Router.run(Routes, function (Handler) {
  React.render(<Handler />, document.getElementById('content'));
});
```

Then, in my FrontendApp.js (the "main" component) I got something like this:
```javascript
class FrontendApp extends React.Component {
  render() {

    // Set active state for back. We should only the back if it is visible!
    let backActive = this.state.backIsActive;

    let panelClasses = [ 'panels' ];
    if(this.state.backIsActive) {
      panelClasses.push('back-active');
    }

    return (
    <div id="page">
      <Notify />
          <Link className="button button-small" to="/"><span>Home</span></Link>
          <Link className="button button-small" to="/help"><span>Help</span></Link>
          <div className="panel-content">
            <RouteHandler />
          </div>
      </div>
    );
  }
}
```

Help Page is just:
```javascript
class Help extends React.Component {
  render() {
    return (
      <div className="help-page">
        Content
      </div>
    );
  }
}
```

Basically you will need to use the RouteHandler Component (provided by React.Router) in your Main Component. Then Content that is drawn by the router will get rendered as content into this RouteHandler Component.

Hope this helps.

**Comment by muraveill** [comment]
That was it. Adding `<RouteHandler />` in RouterTestApp solved it. This line should probably be generated by default, then. Thanks !

**Comment by weblogixx** [comment]
Glad I could help you :-). In the new, hopefully soon to be released version, react.router will not be a part of this software anymore. There will be type of plugins for it.

**Comment by dlombardi** [comment]
I'm having a similar problem with react-router ^1.0.3 where refreshing routes errors out with a cannot get message. Is there anyway to have a catch all, without server-side code, to reroute requests to the appropriate html5 path?

**Comment by weblogixx** [comment]
Hi @dlombardi,

yes there is. In the new version of the generator, you can add the following code to your routes:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Router } from 'react-router';
import Routes from '../utils/Routes';
import history from '../utils/History.js';

// Render the main component into the dom
ReactDOM.render(
  <Router history={history}>
    <YOUR ROUTES />
  </Router />
  document.getElementById('app')
);
```

my utils/History.js looks like this:

```javascript
import { createHistory } from 'history';
export default createHistory();
```

When configuring it like that, you will be able to reload the webpack-dev-server urls on the current route without errors. Hope this helps.

**Comment by dariusk** [comment]
Just for anyone tracking this, in new versions of React you don't need to define a `history`. `react-router` now comes prepackaged with two history singletons. You can just:

```javascript
// hash-based URLs
import {hashHistory} from 'react-router'; 
```

or

```javascript
// use HTML5 pushState
import {browserHistory} from 'react-router'; 
```

[More info here](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#using-history-with-router).

**Comment by SkylerHu** [comment]
```
// service.js
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config');

new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  contentBase: config.devServer.contentBase,
  hot: true,
  historyApiFallback: true
}).listen(3000, 'localhost', function (err, result) {
  if (err) {
    return console.log(err);
  }

  console.log('Listening at http://localhost:3000/')
});
```
I resolved it by add `contentBase: config.devServer.contentBase`.

**Comment by tony2tones** [comment]
I came across the same problem, if you have a server that responds to requests and a HashRouter if you are using a static file server. Instead of using BrowserRouter use HashRouter its not the perfect fix, but should solve the cannot GET "/path" error. be sure to import HashRouter from 'react-router-dom'

    render() {
        return (
            <div>
                <HashRouter>
                    <Blog />
                </HashRouter>
            </div>
        );
    }

source: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/basic-components.md

**Comment by thestig993** [comment]
@SkylerHu Thanks a lot, after some time I finally make it work

**Comment by Rohit221990** [comment]
#webpack.config.js   

 devServer: {
        port: 3001,
        publicPath: '/',
        historyApiFallback: true
    }

**Comment by SHAGGYER** [comment]
in package.json, add "proxy": "localhost:5000" or whatever port your express app is running on

**Comment by SHAGGYER** [comment]
im not having this error on localhost, but i am in production. any ideas?

**Comment by dimo121** [comment]
I had a similar problem with cannot GET /path message, I could only render the main page. 

I went on to use Link in a navbar to each path and they loaded succesfully. I'm not sure of the other solutions but when typing in the path manually I get the same error.
