### ISSUE TITLE
npm script is gone

### ISSUE THREAD

**Issue by james4388** [newtriks/generator-react-webpack#147]
I cannot use `npm start` anymore only `grunt serve` work, any idea?

**Comment by weblogixx** [comment]
@james4388: Hi James, could you please tell me which version of the generator you are using? In Versions before 2.0, there is no npm start command in generator-react-webpack. This is only available in 2.x.x.

Offtopic:
@newtriks: I just checked and it seems that the package is not updated on npm. Could you please run a npm publish so the new version can be downloaded? Thanks.

**Comment by newtriks** [comment]
Done


On Thursday, 1 Oct 2015 at 07:55, Chris <notifications@github.com>, wrote:

@james4388: Hi James, could you please tell me which version of the generator you are using? In Versions before 2.0, there is no npm start command in generator-react-webpack. This is only available in 2.x.x.


Offtopic:
@newtriks: I just checked and it seems that the package is not updated on npm. Could you please run a npm publish so the new version can be downloaded? Thanks.

**Comment by weblogixx** [comment]
Closing this as there was no feedback for 20 days. If the problem still persists, please just open a new ticket. Thank you!
