### ISSUE TITLE
Error executing 'yo react-webpack' -> Unexpected sctrict mode reserved word

### ISSUE THREAD

**Issue by romanrdgz** [newtriks/generator-react-webpack#149]
I'm new to JS and React, and I'm trying to start with your generator in a Koding VM. I just installed nodejs and npm with ubuntu's apt-get, and then installed yo, grunt-cli, karma and react-webpack from npm just as you suggest in your blog post http://newtriks.com/2013/12/31/automating-react-with-yeoman-and-grunt/

Then, when I execute the command:
    $ yo react-webpack

I get the following:
/usr/local/lib/node_modules/generator-react-webpack/generators/app/index.js:2
let generator = require('yeoman-generator');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._storeAsPath.Object.defineProperty.get [as react-webpack:app] (/usr/local/lib/node_modules
/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.j
s:243:16)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environmen
t.js:261:24)

How to proceed?

**Comment by nepalez** [comment]
+1
Exactly the same problem

**Comment by weblogixx** [comment]
Hi,

seems like the version of node.js you are using is too old. You have to use a version of greater than 4.0 to run the generator. Older node versions (like 0.12) are not going to work because it is built using ES2015. If updating is not an option for you, you could try to use the --harmony flags of node 0.12. However, I have not tried that yet.

The engine is also specified in package.json, so it should warn you when installing with an older node version.

**Comment by nepalez** [comment]
@weblogixx Thank you, Chris for clearing that.
Yes, I have to use `nodejs-legacy` to fix `this problem](http://blog.legacyteam.info/2014/12/getting-yeoman-work-ubuntu/) under `ubuntu 14.04`.

**Comment by romanrdgz** [comment]
Using nodejs-legacy didn't worked out for the Ubuntu version being used in Koding virtual machines. I also tried adding ppa:chris-lea/node.js repository and go with nodejs after an apt-get update to achieve it. The result is the same error.

The strange thing is that nodejs -v reports 0.10.37 yet, even with the PPA. I'll try to update in a different way nodejs to solve it

**Comment by weblogixx** [comment]
@nepalez: Debian and Ubuntus versions of node are always quite old, even in unstable/testing Debian versions. A more simple way to use it would be nvm (https://github.com/creationix/nvm) which gives you the possibility to use multiple node versions on the same machine. You can always switch or set the default with it, so node updates get a lot easier (at least unter unix based systems, on Windows you will need another software to do this).

If you can live without the apt installation, its a viable (and highly recommended) option.

**Comment by romanrdgz** [comment]
new attempt:
    $ wget -qO- https://deb.nodesource.com/setup_4.x | sudo bash -
    $ sudo apt-get install nodejs
    $ nodejs -v
    -> 4.1.2
    $ npm -v
    -> 1.4.3

The error is still happening though

**Comment by weblogixx** [comment]
I cannot see any errors happening with any version from 4.0.0 onwards (just tested it on all available ones). Still seems like an installation error. Would you mind installing via nvm? It wont set the default version if it is not explicitly told to do so.

Just install via `wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash`, install a new node version (via nvm install 4.1.2) and then use it in this shell (via nvm use 4.1.2). It should then use the nvm ecosystem for THIS shell only. Try again to run it.

I don`t know the installer-package from nodesource.com, maybe it does not set the node version application wide?

**Comment by nepalez** [comment]
@weblogixx Thank you. I've installed nvm and it just works :)

**Comment by weblogixx** [comment]
@nepalez: You are welcome. Glad I could help.

**Comment by zhx828** [comment]
I know this issue probably has been solved, but I still have similar issue. I'm using npm -v 3.5.3 and node -v v.0.10.32 Should I do any updates on them? I think I updated to the newest version. Thanks
