### ISSUE TITLE
Autoprefixer support?

### ISSUE THREAD

**Issue by CezarLuiz0** [newtriks/generator-react-webpack#153]
There is already support?

**Comment by weblogixx** [comment]
Hi @CezarLuiz0,

it is currently not planned to add autoprefixr support. We want to stay as "bare bone" as possible with this generator. In fact, it should not be too hard to include it. Just include https://github.com/passy/autoprefixer-loader into your project and adjust the basic webpack configuration (in the cfg folder) for css files like this:

```javascript
loader: 'css-loader!autoprefixer-loader'
```

This should add autoprefixr support for all css files. If you use less, sass, ..., then just add the autoprefixer-loader for those settings
