### ISSUE TITLE
Providing application configuration based on --env variable

### ISSUE THREAD

**Issue by sthzg** [newtriks/generator-react-webpack#154]
What do you think about providing modules for environment-based application configuration out of the box?

As a first approach I set the `NODE_ENV` to the `env` variable that gets set in `webpack.config.js`:

```javascript
// Set the correct environment
var env;
if(args._.length > 0 && args._.indexOf('start') !== -1) {
  env = 'test';
} else if (args.env) {
  env = args.env;
} else {
  env = 'dev';
}
process.env.NODE_ENV = env;
```

Then I updated `cfg/base.js` with an alias for `config`:

```javascript
  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      // ...
      config: `${srcPath}/config/${process.env.NODE_ENV}`
    }
  },
```
Now it is possible to `import config from 'config';` and whatever is exported from `src/config/<env>.js` will be available.

If this sounds reasonable I could provide a PR that also creates the config files when generating a project (of course it could be through a different approach like not touching `NODE_ENV` but reusing the `env` variable from `webpack.config.js` or whatever is the least obtrusive way). Otherwise feel free to drop that issue.

**Comment by weblogixx** [comment]
Hi @sthzg, seems like an interesting idea.
If you want please pull it to https://github.com/weblogixx/react-webpack-template, because thats where the configs are getting created.

Thanks!

**Comment by sthzg** [comment]
@weblogixx thanks for your reply and the guidance to the correct repo. I've added an issue and a first draft there, so I guess the issue here could be closed.

**Comment by weblogixx** [comment]
@sthzg: You are welcome :).
