### ISSUE TITLE
Including bower components

### ISSUE THREAD

**Issue by be-codified** [newtriks/generator-react-webpack#157]
Hi,

how can I include bower components? They should be located in root.

Should I include them in index.html or in Main.js? I think I am having problem accessing bower components folder because it is parent of src folder.

Thank you in advance.

**Comment by weblogixx** [comment]
Hi @be-codified, I will look into this and update the Generator with this feature. In the mean time, you could look if the given module you want to include is not also available via the npm registry.

**Comment by weblogixx** [comment]
Hi @be-codified,

I just updated the generator to include support for bower. I tested it with:

```
bower install jquery

# src/components/MainComponent.js
var jq = require('jquery');
console.log(jq);
```

Newly generated projects should now have bower support. If you want to include it in already set up projects, just add the adjustments from https://github.com/weblogixx/react-webpack-template/commit/827dd86a3cd2fc52d2918a84bd2e416b92e05320.

Hope this helps :)

**Comment by be-codified** [comment]
Hi @weblogixx,

thank you :)

**Comment by weblogixx** [comment]
You are welcome :)
