### ISSUE TITLE
Coverage report

### ISSUE THREAD

**Issue by camjc** [newtriks/generator-react-webpack#158]
Being able to see code coverage is a minimum requirement for many projects, and since this generator sets up testing for you it would be great if it would give you a coverage report too.

**Comment by camjc** [comment]
I managed to set it up in my project in this PR https://github.com/Adslot/alexandria/pull/9/files

Haven't been able to get it to output the ES2015 code in the coverage html though.

**Comment by weblogixx** [comment]
@camjc: Yes, currently the support is missing. Did not even think about it :(. Thanks for the request, will add it in one of the later versions of the generator.

**Comment by weblogixx** [comment]
@camjs: Support is now integrated with the release of react-webpack-template 0.3.2. Please update the generator so it can fetch the new version. New projects should then always include coverage reports. Thanks again for the hint :)
