### ISSUE TITLE
Suggestion: Webpack require should resolve jsx by default

### ISSUE THREAD

**Issue by umbrae** [newtriks/generator-react-webpack#16]
I had to add:

``` javascript
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
```

To my webpack config so that jsx files could be easily `require` without being explicit about extension names. I'm still a noob at most of this but it seems like this may be handy for others.

**Comment by kswope** [comment]
:+1: to more convention, less configuration

**Comment by Benno007** [comment]
Using an empty extension in the array no longer works in the latest version of webpack (2.2.0). Anyone have a workaround?

**Comment by selbekk** [comment]
@Benno007 simply skip the empty extension:

```javascript
resolve: {
  extensions: ['.js', '.jsx']
}
```
