### ISSUE TITLE
black screen when running 'npm run serve"

### ISSUE THREAD

**Issue by rcholic** [newtriks/generator-react-webpack#160]
I created a react-webpack project using this generator, however, after I run `npm run dist` and `npm run serve` in the terminal, I see the following line with a black screen underneath it in the browser. What might be going wrong? or how to build and run this project?

`App hot update.`
|----------------------
|  BLACK            |
|  screen             |
______________

**Comment by weblogixx** [comment]
Hi @rcholic,

could you provide me with a little more information?

- OS (and Version)
- Where did you run the command from (cmd.exe or PowerShell on Windows, Bash on Linux/OSX)
- What are your node and npm versions?
- which version of the generator do you have installed (npm ls -g)?
- Is it a new project or did you already add components or other stuff?
- What Browser do you get the error in?
