### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by stylesuxx** [newtriks/generator-react-webpack#162]
Hey guys,
first of all a big **thank you** for your hard work on this really awesome generator.
Have been experimenting with/using it quite a lot lately.

Last week I fell in love with [CSS Modules](https://github.com/css-modules/css-modules) and added them to my template generated by your generator and was wondering if this is something worth giving back...

In case you want this functionality added, let me know and I will gladly submit a PR.

**Comment by weblogixx** [comment]
Hi @stylesuxx,

I will have a look at it. For a rule of thumb: If it just is the basic integration (like with sass and less) we could ship it without problems. However, I do not want to integrate the whole toolchain, because we want this generator as slim as possible.

If that sounds ok for you, just open a PR and I will add it when I have some spare time. It could take until end of this week because I am on holidays...

**Comment by stylesuxx** [comment]
Hey @weblogixx, sounds good to me.
For CSS Modules to work properly there need to be some major changes in how the CSS is used. Instead of requiring the CSS it is imported, also the CSS classes need to be set in a slightly different way. On the other hand it sits on top of sass/less/...

The changes for #163, in the way you suggest, would only be a minor change - one additional prompt, one additional dependency and a minor addition to the webpack config.

I guess I will provide a PR for #163 first, then prepare one for this issue and see if you like it.

No hassle, I do not even know if I can make it this week ;-) So have nice holidays.

**Comment by weblogixx** [comment]
@stylesuxx:
After checking https://github.com/weblogixx/react-webpack-template/pull/12, I too think we should add it in the generator, not the template itself. Lookin forward to a pr from you :+1: :)

**Comment by mr-wildcard** [comment]
+1
https://github.com/gajus/react-css-modules ?

**Comment by weblogixx** [comment]
@stylesuxx: I know this has been open for a long time. Support for this will finally be there when the new version of the template is ready. It already supports css modules (named ones, so you may still use regular css) per default. I am currently working to get paths straightened for the new version of the generator, the styles directory will also vanish (excluding legacy projects, which will apply styles the old way). Hope I will be able to push the new version soon, at least as beta release...
