### ISSUE TITLE
stylus-loader warnings

### ISSUE THREAD

**Issue by abienz** [newtriks/generator-react-webpack#170]
When I run the generator with stylus as my chosen CSS Preprocessor I get the following warnings:
```
npm WARN EPEERINVALID stylus-loader@0.5.0 requires a peer of nib@~1.0.4 but none was installed.
npm WARN EPEERINVALID stylus-loader@0.5.0 requires a peer of stylus@~0.49.2 but none was installed.
```

This causes page load errors such as the following:

```
Errors while compiling. App updated with errors. No reload!
Cannot find module 'stylus'
 @ ./src/styles/TimeSlice.styl 4:14-128 13:2-17:4 14:20-134
```

I made the build work for me by adding...
```
,
    "stylus": "latest",
    "nib": "latest"
```
To my package.json devDependencies but I don't suppose this is an ideal fix

**Comment by weblogixx** [comment]
@abienz: There where problems with unmet peer dependencies, the problem was fixed in 3.1.1. Please update your generator, it should work fine then.
