### ISSUE TITLE
App stuck at 'wait until bundle finished: /assets/app.js'

### ISSUE THREAD

**Issue by HarrisRobin** [newtriks/generator-react-webpack#171]
So, for some reason the app won't get past ```wait until bundle finished: /assets/app.js``` when I run 'npm start' or 'npm run serve'. 

Also, 'npm run dist' gets stuck at ```> copyfiles -f ./src/index.html ./src/favicon.ico ./dist``` 

Anyone running into this issue as well? 

I am on node v5.0.0
Latest version of the generator.

I have been using this for a week now without a problem, so im not sure what is causing it now.

**Comment by HarrisRobin** [comment]
UPDATE: I am now able to reproduce this.

Only way to get out of this problem that throws no error is by going to ```Main.js``` , removing all the components ```import```, restarting the server and when app is ready putting them back in. 

Anyone who runs into this, please see if you can reproduce as well. I will leave this open but feel free to close if no one runs into this issue.

**Comment by HarrisRobin** [comment]
UPDATE2: even though I got around the issue above, ```npm run dist``` still does not get past ```> copyfiles -f ./src/index.html ./src/favicon.ico ./dist```

<img width="655" alt="screen shot 2015-11-26 at 22 32 47" src="https://cloud.githubusercontent.com/assets/3880008/11433626/a838ab60-948d-11e5-8878-3236180cf9e5.png">

**Comment by HarrisRobin** [comment]
Removing the components again, I get this when running 
```npm run dist```
<img width="1074" alt="screen shot 2015-11-26 at 22 53 19" src="https://cloud.githubusercontent.com/assets/3880008/11433804/b3649fdc-9490-11e5-967d-86b3ff5d30d1.png">

**Comment by weblogixx** [comment]
Hello @HarrisRobin,

Interesting, I do not had such problems once. Could you please provide a link to the code where the error  happens? Also, which operating system are you working on?

**Comment by HarrisRobin** [comment]
@weblogixx I am on OSX. and I cannot host it because I can't even build the project. However, here is a repo: https://github.com/HarrisRobin/react-flux-movie-UI

**Comment by weblogixx** [comment]
After just skimming through the code a bit, the only thing that I see that could cause problems is the way you incloude node-bourbon in the config. 

I will have a closer look over the weekend.

**Comment by HarrisRobin** [comment]
@weblogixx interesting. what red flags do you see? ```@import bourbon;``` is working just fine fyi.

**Comment by weblogixx** [comment]
Hi @HarrisRobin,

had another look at it. There are known problems with bourbon in webpack configs. Someone worked around these and build https://github.com/lowik/bourbon-sass-loader. Maybe you should try this out. When I check out your repo and just remove the Aside.scss require statement it builds. Seems like it really has to do with the way that webpack tries to build the dependencies.

As I am no sass expert by myself, someone else may help here?

**Comment by HarrisRobin** [comment]
@weblogixx thanks for the feedback. I will try the bourbon-sass-loader and report back if it works :)

**Comment by HarrisRobin** [comment]
@weblogixx just wanted to come back and say that i don't think the problem is with bourbon. removing bourbon completely did not solve my issue and I still have to do the same thing in order to get the project to compile and work (remove the highlighted block of stuff in the screenshot, re-run npm start and then add them again)

<img width="739" alt="screen shot 2015-11-30 at 22 42 00" src="https://cloud.githubusercontent.com/assets/3880008/11491839/a38d5bb4-97b3-11e5-8b47-f672942588aa.png">


I will keep digging and figure out what's going on. I'll also try doing it from a project from scratch and see.

**Comment by HarrisRobin** [comment]
Yeah so unless I reduce the amount of components or remove them before i run ```npm start``` then the app never finishes to bundle and it gets stuck on :

```webpack: wait until bundle finished: /assets/app.js``` infinitely. I ruled out bourbon as the issue and don't really know what's going on.

**Comment by weblogixx** [comment]
@HarrisRobin: I think I identified the problem know. https://github.com/jtangelder/sass-loader/issues/168 brought me closer to it. Seems like the sass version shipped with the generator is way too old. In the meantime it made a jump from 1.0 to 3.1. The following works for my setup, hope for yours too:

- First, ```npm uninstall sass-loader```
- Remove the sass-loader from npm config
- Run ```npm install --save sass-loader```. It should now be installed with the latest version (3.1.x)
- Start your project.

After going this steps, it should work the way it is expected. There was a threadpool limit that gets hit in the old version of sass-loader and node-sass. This seems to cannot be fixed without updating the plugin.

In any case, I will update the dependencies for sass.

Please tell me if this helps.

**Comment by HarrisRobin** [comment]
@weblogixx spot on! that was it.

thanks for the fix :)
cheers

**Comment by tusharmath** [comment]
@weblogixx I am facing the exact same issue, but I am not using any of above mentioned packages. —
```bash
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack: wait until bundle finished: /
```

The `index.html` file is being created via a custom plugin that I have written. It's highly possible that's the culprit but I am not sure why. My logic is simple — I listen to the `emit` event on the compiler and create my `index.html` file. Once the file is generated I call the `callback`.

**Comment by weblogixx** [comment]
Hi @tusharmath,

have you tried with the built in index.html? If you need a custom index.html generated, you could also have a look at https://github.com/ampedandwired/html-webpack-plugin.

If not, please provide a link to your repo if this is possible.

Thanks!

**Comment by tusharmath** [comment]
@weblogixx Thanks for responding. There was a ridiculously lame bug in my code. I was using RxJS to listen to the `emit` event using the [fromCallback](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromcallback.md) operator which only gets fired once. 

I should have used the [fromEventPattern](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromeventpattern.md) to convert the `emit` events into a stream and then consume.

**Comment by nrvakil** [comment]
using an older version of node worked for me: v12.18.4 to v10.18.1
