### ISSUE TITLE
Use babel-eslint as parser ?

### ISSUE THREAD

**Issue by mr-wildcard** [newtriks/generator-react-webpack#173]
because this cool project generates ES2015 stuff, and soon ES2016 we hope.

And:
> Given the recent developments in the world of parsers, I think that using babel-eslint is the best way to play with cutting edge features like this. https://github.com/babel/babel-eslint

> That means you don't have to wait for us, and we don't need to worry about constantly updating experimental features.

from https://github.com/eslint/eslint/issues/1657#issuecomment-77500655

Default parser couldn't handle http://babeljs.io/docs/plugins/transform-object-rest-spread/ plugin I my case.

**Comment by weblogixx** [comment]
@mr-wildcard: Sounds like a good idea. I will play around with and check if it can be easily integrated (as stated on the project page, that should be the case).

**Comment by mr-wildcard** [comment]
:+1: 

In case it's ok for you @weblogixx,
These change needs two simple steps:

* adding `babel-eslint` as `devDependency`
* adding `"parser": "babel-eslint",` in `.eslintrc` file

**Comment by weblogixx** [comment]
@mr-wildcard: Just added it to the underlying template. It should be available after updating your installed generator.

**Comment by mr-wildcard** [comment]
:100:  thx @weblogixx
