### ISSUE TITLE
Default css creates white text input fields with white text

### ISSUE THREAD

**Issue by aragacalledpat** [newtriks/generator-react-webpack#176]
Thanks so much for making this generator!  

I have been using it today to learn React, and this styling issue confused the crap out of me.  I assumed React wasn't updating the DOM correctly or something.

**Comment by weblogixx** [comment]
Hi @aragacalledpat,

first, thank you. Could you be a bit more precise about your issue? Thanks!

**Comment by aragacalledpat** [comment]
Sure!  Sorry for not describing it better in the first place.

Right after running the generator, I added <input type="text"></input> to the App Component.  The input is rendered with a white background color and white text color.  So, the text is invisible.  

body { color: #fff} is set in the style sheet and it's cascading down to the input element.  Obviously it's a quick fix and not a big deal but I thought it might be worth bringing to your attention.  Because I'm new to React, I assumed it was happening because there was something wrong with my React code.

**Comment by weblogixx** [comment]
Ah, now I get it. I do not think that we have to fix this as most people will always right out delete the content of the main css file. However as you are just starting out, would you mind to give some feedback about the generators usage when you tried it? When you are a beginner, you will see some things different from someone who has worked with react for a time. Maybe we could make the docs (or some functions) more beginner friendly with some added feedback.

If you would like, just open a new issue with your problems.

Thanks,
Chris

**Comment by aragacalledpat** [comment]
I would be happy to give some feedback.  Thanks for inviting me to contribute : )

**Comment by weblogixx** [comment]
You are welcome :)
