### ISSUE TITLE
Destructuring assignment support

### ISSUE THREAD

**Issue by firebait** [newtriks/generator-react-webpack#177]
Hi,

I tired to do the following on a component:

```
let { disabled, ...other } = this.props;
```
and got the following:
```
Module build failed: SyntaxError: /xxx.jsx: Unexpected token (26:20)
  24 |   render () {
> 25 |     let { disabled, ...other } = this.props;
     |                     ^
```
Any ideas would be helpful. I tried adding options to the .eslintrc file with no avail.

**Comment by stylesuxx** [comment]
Hey @firebait,
*.eslintrc* is only for the lint settings.

What you are trying to to is to spread rest properties, this is *not part* of **es2015** but is a state 2 proposal, so just install the state 2 presets:

```Bash
npm install babel-preset-stage-2 --save-dev
```
and activate them via *.babelrc*:
```JSON
{
  "presets": [
    "es2015",
    "react",
    "stage-2"
  ]
}
```

and you should be good to go.

**Comment by firebait** [comment]
Thanks @stylesuxx that did it.

**Comment by thibault** [comment]
This thread solved the problem for me. Since I was also searching the correct eslintrc config to recognize the spread operator, I will leave this here for the ones who will follow me:

    // ~/.eslintrc.js
    module.exports = {
      'parserOptions': {
        'ecmaFeatures': {
          'experimentalObjectRestSpread': true
        }
      }, …
