### ISSUE TITLE
generator-react-webpack-redux

### ISSUE THREAD

**Issue by stylesuxx** [newtriks/generator-react-webpack#178]
Alright, I think I am done for the most part with [generator-react-webpack-redux](https://github.com/stylesuxx/generator-react-webpack-redux)

Tests are in place and passing, dependencies are up to date and it is published to NPM.

@weblogixx: I set myself as author and added you as contributor. I did this so you don't get blamed for issues in the redux generator. I hope this is OK with you.

Other than that I would of course love to hear feedback if you take it for a test ride :-)

I am also spreading the word among my friends to get some feedback.

**Comment by weblogixx** [comment]
Hi @stylesuxx,

thats more than ok for me. Thank you for all your contributions so far.
I will look into it next week and give you some feedback if I find something noteworthy.

You are also free to add a pr to this repositories README.md to add your generator in the (currently very short...) generators list.

**Comment by weblogixx** [comment]
Seems really nice :+1:! I am currently investigating in the ast parsing part you did for adding some lines to the alt generator and may have a deeper look at the style path issue we talked about.

Hope you will get many users with this thing.
