### ISSUE TITLE
Components style

### ISSUE THREAD

**Issue by stylesuxx** [newtriks/generator-react-webpack#180]
I asked a fried of mine, namely @zerocity to give some feedback on [generator-react-webpack-redux](https://github.com/stylesuxx/generator-react-webpack-redux) and I think he did not grasp, that I am building on top of another generator, so I will forward his feedback as I feel appropriate.

He states that it would be more logical to have the styles directly with the component in a structure like so:
```
- ComponentName
    - styles
      - ComponentName.[css/less/sass]
    ComponentName.js
```

Which I think is true especially in context of component re usability you would have everything in one place regarding a single component.

@weblogixx: let me know what you think - and I will provide a PR.

**Comment by weblogixx** [comment]
That would be nice I think. This is a breaking change for current projects that use the workflow of today. Will think about it and report in later.

**Comment by stylesuxx** [comment]
We could also add this as an option, and let the user choose. The "all in one" could be default from now on. This way we would not break anything but "soft force" the users to use the "all in one" style and thus let the "old" method fade out.

**Comment by weblogixx** [comment]
Hi @stylesuxx,

one of the latest changes I made in the current master here was the addition of the major version of the generator (3.x currently) as an option. We are now able to guess the paths of generated components. I just have to add the legacy layer in the next version 4.0.

Currently I am working on the second version of the react-webpack-template, using webpack 2 and unit testing with enzyme and mocha (without karma), which will speed tests up far more than I expected.

It would be nice to hear your opinion on these changes. Just clone https://github.com/weblogixx/react-webpack-template/tree/2.x and try it out if you want to.

I will start development of 4.x when the template is ready for productional use (currently, some things like less, sass, recss...) are not implemented.
