### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by stylesuxx** [newtriks/generator-react-webpack#182]
Hey @weblogixx what do you think about a slack channel, I think it would be cool to have a place to hang out and I would not need to spam the issue section so much :-)

**Comment by weblogixx** [comment]
I think thats a nice idea. Will create one this week :+1:

**Comment by yordis** [comment]
@weblogixx all the community of react is in Discord right now. I suggest you to ask for some channel there will be very helpful for everyone

**Comment by weblogixx** [comment]
@yordis, sorry, I don`t quite understand what you mean. Could you elaborate this some more?

**Comment by yordis** [comment]
:laughing:

**Comment by stylesuxx** [comment]
I saw you were marking issues with Milestone 4. Willing to help with those - but a quick communication channel would be cool - so I am pushing this. Hell, even an IRC chan on freenode would be enough :-)

**Comment by weblogixx** [comment]
Hey @stylesuxx,

I know I am kind of late for this request, but anyways... I just created a gitter channel for the generator (https://gitter.im/newtriks/generator-react-webpack). Hope we will have some conversations about the future of the project. Will add a badge for it in the readme soon.

Hope this will make it easier to follow the changes of this project.
