### ISSUE TITLE
cannot start the server

### ISSUE THREAD

**Issue by pravinbashyal** [newtriks/generator-react-webpack#183]
The following error occurs when I start the server after initial install: 

    > toDo@0.0.1 start /home/pravin/learns/to-do
    > node server.js --env=dev

    module.js:339
        throw err;
        ^

    Error: Cannot find module '../../modules/es6.object.assign'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/home/learns/to-do/node_modules/core-js/fn/object/assign.js:1:63)
        at Module._compile (module.js:435:26)
        at Object.Module._extensions..js (module.js:442:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)

    npm ERR! Linux 4.2.0-19-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
    npm ERR! node v4.2.3
    npm ERR! npm  v2.14.7
    npm ERR! code ELIFECYCLE
    npm ERR! toDo@0.0.1 start: `node server.js --env=dev`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the toDo@0.0.1 start script 'node server.js --env=dev'.
    npm ERR! This is most likely a problem with the toDo package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node server.js --env=dev
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls toDo
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/learns/to-do/npm-debug.log

**Comment by weblogixx** [comment]
Hi @pravinbashyal,

I do not get such errors when generating new projects (or using the underlying tempalte directly).
Seems like maybe some modules (in this case core-js) where not correctly installed. Just run npm install in the root dir of your toDo application and try it again.

**Comment by weblogixx** [comment]
@pravinbashyal,

there was nothing new in 2 weeks. I assume the error is no more. Please feel free to submit a new issue or reopen this one if this should not be the case.
