### ISSUE TITLE
Question about component naming convention

### ISSUE THREAD

**Issue by BobWhitelock** [newtriks/generator-react-webpack#186]
Hi, first off thanks for the generator, it really helps with getting a project started quickly. I just have a quick question about the naming scheme used for components when using the component generator. Components generated by this always have a 'Component' suffix appended to them, this seems odd and unnecessary to me for a couple of reasons:
- I've not seen this convention in any other React project or library, components are normally just given the name of what they are e.g. react-bootstrap's progress bar is just called ProgressBar;
- it's always obvious anyway which classes are components without this, as these are the camel-cased classes imported from files with camel-cased names within the components directory;
- if someone does want their components to be named in this way they could always add 'component' to the name when calling the generator anyway.

Anyway, this doesn't actually effect anything and is easily changeable, but just something I was wondering about the reasoning of, thanks.

**Comment by weblogixx** [comment]
Hello @BobWhitelock,

the component suffix seems to be redundant indeed. It was there before version 2.0 was created, so we left it unchanged when rewriting the generator. There are some plans for a version 4.0. The removal of the suffix will also be included then. Hope this helps.
