### ISSUE TITLE
arrow function will throw syntax error

### ISSUE THREAD

**Issue by tryer3000** [newtriks/generator-react-webpack#187]
first, I'm new to front-end, so this may not be a problem of this generator

arrow function fails to build.

Insert the following code into AppComponent

```
  xyz = () => { this.x = 2; };
```
This work  in [babel 5](https://babeljs.io/repl/)

**Comment by tryer3000** [comment]
Well, I've just learnt that:
It's a feature of es6 stage0.

**Comment by StoneCypher** [comment]
This is completely misunderstood

**Comment by StoneCypher** [comment]
you probably just didn't install the babel presets, or something.

babel does implement arrow functions.

**Comment by belal-mazlom** [comment]
Check this page:
http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/
You need to add "stage-0" preset

```
module: {
  loaders: [
    {
      loader: "babel-loader",

      // Skip any files outside of your project's `src` directory
      include: [
        path.resolve(__dirname, "src"),
      ],

      // Only run `.js` and `.jsx` files through Babel
      test: /\.jsx?$/,

      // Options to configure babel with
      query: {
        plugins: ['transform-runtime'],
        presets: ['es2015', 'stage-0', 'react'],
      }
    },
  ]
}
```

**Comment by weblogixx** [comment]
Hi @belal-mazlom,

the article is kind of outdated. Arrow-Functions are currently supported in babel by using es2015. You can see the implementation details of the generator [here](https://github.com/react-webpack-generators/react-webpack-template/blob/2.x/.babelrc) (for the beta) or [here](https://github.com/react-webpack-generators/react-webpack-template/blob/master/.babelrc) for the current stable. State-0 is not needed to transform for arrow anymore. You can just add it to .babelrc.

**Comment by StoneCypher** [comment]
this issue has been closed for three years. please don't spam it with works for me.
