### ISSUE TITLE
npm run dist error appear when i distributed my code. 

### ISSUE THREAD

**Issue by uinika** [newtriks/generator-react-webpack#189]
below is my project.
https://github.com/uinika/saga.git

* my code is not packaged correctly and there is no error info outputs. PLS, checkout my project, and test it. 
(1) clone my code and enter the project folder. 
(2) take "npm install" .
(3) run "npm start" will be ok. but "npm run dist" didn't.

**Comment by weblogixx** [comment]
Hello @uinika,

I have just looked into this issue. It seems like there is a known problem in webpack for bigger projects, as described in https://github.com/webpack/webpack/issues/537.

It seems to be related to the UglifyJsPlugin. If you adjust your dist config like this:

```javascript
'use strict';

let path = require('path');
let webpack = require('webpack');
let _ = require('lodash');

let baseConfig = require('./base');

// Add needed plugins here
let BowerWebpackPlugin = require('bower-webpack-plugin');

let config = _.merge({
  entry: path.join(__dirname, '../src/index'),
  cache: false,
  devtool: 'sourcemap',
  plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new BowerWebpackPlugin({
      searchResolveModulesDirectories: false
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: false
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.NoErrorsPlugin()
  ]
}, baseConfig);

config.module.loaders.push({
  test: /\.(js|jsx)$/,
  loader: 'babel',
  include: [].concat(
    config.additionalPaths,
    [ path.join(__dirname, '/../src') ]
  )
});

module.exports = config;
```

it will compile, however it will NOT compress the contents anymore. If you still need that, you may manually use uglify.js to parse the app.js in the dist-directory.

Hope this helps! I will have an eye on this error as it may need some corrections in our webpack configuration, too. Unfortunately, there is currently no other way to fix this (at least that I would know of).

**Comment by uinika** [comment]
@weblogixx 
Many thanks. I have already fixed this issue, but unfortunately i was spend much time on this.
`
    plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
  ],
`
