### ISSUE TITLE
How to disable overlay with hot reload?

### ISSUE THREAD

**Issue by fyyyyy** [newtriks/generator-react-webpack#192]
Apparently this uses react hot reload which uses the webpack hot middleware.
Setting overlay:false should disable the info bar at the top of the dom. However it doesnt seem to have any effect.

Thanks

**Comment by fyyyyy** [comment]
![image](https://cloud.githubusercontent.com/assets/3744048/13346286/71b494bc-dc65-11e5-94eb-8c72f649a58d.png)

**Comment by floydprice** [comment]
Hey @fyyyyy you can do it by changing the following line in the generated server.js

`open('http://localhost:' + config.port + '/webpack-dev-server/');`

to

`open('http://localhost:' + config.port + '/');`

Hope that helps.

**Comment by fyyyyy** [comment]
Awesome, thanks :+1:
