### ISSUE TITLE
Does sourcemap have no effect?

### ISSUE THREAD

**Issue by qcgm1978** [newtriks/generator-react-webpack#193]
Hello:
        The devtool console prompt many ''//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.' 
        Dose it indicate sourcemap have no effect?

**Comment by weblogixx** [comment]
Hi @qcgm1978,

Sourcemaps are generated via webpack and they do not seem to be configurable. I think you will have to wait until webpack updates its sourcemap generation code.

However, both webpack generated sourcemaps (dev and dist) are just working fine for me in all browsers.

Hope this helps.

**Comment by qcgm1978** [comment]
Ok,I'll check it effective or not.thank your help:)
