### ISSUE TITLE
WebpackDevServer config inheritance problem

### ISSUE THREAD

**Issue by GryfonN** [newtriks/generator-react-webpack#194]
All WebpackDevServer configs (for specific env) are singletons and loaded together in _webpack.config.js_, so they override base config together.

Example: When I added proxy property in _cfg/dev.js_, and started app with _npm run serve:dist_, my proxy setting was added to _base.cfg_ and used also for _dist.cfg_.

I fixed this problem in a way that I load only one config according _validEnv_ variable in _buildConfig()_ method and not all of them.

**Comment by weblogixx** [comment]
Hi @GryfonN,

I am aware that such a problem existed, as we extended the base configuration in the older versions of the generator. Since version 2.3.1 of the generator, this should not be the case anymore.

Could you post an example of your config so I can check it against the latest version?

**Comment by GryfonN** [comment]
[Gist: webpack.config.js](https://gist.github.com/GryfonN/7f73c2eec9908ad69341#file-webpack-config-js)

**Comment by weblogixx** [comment]
Hi @GryfonN,

thanks for pointing it out, I will add the adjusted configuration to the underlying template. The new version will be available tomorrow.
