### ISSUE TITLE
Add "mocha" to the "env" list of .esltinrc

### ISSUE THREAD

**Issue by louisremi** [newtriks/generator-react-webpack#195]
Hi, 

My editor is configured to automatically lint all files when an .eslintrc file is present, and files in the test/ dir don't validate because mocha isn't listed as en environment in the .eslintrc
I wish I could've made a PR to propose that change, but I couldn't locate the template for this file.

**Comment by weblogixx** [comment]
Hi @louisremi,

I have just added this feature in a new release. It should work now for newly generated projects.
The code you are looking for is located in https://github.com/weblogixx/react-webpack-template. This is the standalone version of the webpack config used by the generator.
