### ISSUE TITLE
Missing dev dependecies

### ISSUE THREAD

**Issue by GryfonN** [newtriks/generator-react-webpack#203]
It would be good to include all modules to package.json that are need for features of this generator.
For me I had to install **sass-loader** and **node-sass** by my own ad save it with --save-dev, when I wanted use my .scss files, that are supported with base config

**Comment by weblogixx** [comment]
Hi @GryfonN,

the dependencies get saved to package.json when you set up a new project. If you choose less, you will get less loader, if you choose sass, you will get sass loader and so on. This is done as someone who needs less or sass only does not need the loader for the other one for his project.

If you choose to roll with just css, then no additional loader will be installed as dependency.

You can see the additional loaded modules at https://github.com/newtriks/generator-react-webpack/blob/master/utils/configopts.json in about line 70.

Installation of a new project did include them without any problems for me.

**Comment by GryfonN** [comment]
Thx for explanation. I have chosen during set up of project just less, and then I decided to use scss :) 
I saw that loader configuration for webpack is already there so I thought that I would be able to use scss out of box.
