### ISSUE TITLE
Is there any way to hide the warnings in browser console?

### ISSUE THREAD

**Issue by madwiki** [newtriks/generator-react-webpack#205]
I find that too many warnings in browser console,and they are increased by hot loading.
Is there any way to hide the warnings in browser console?

I have tried to use `noInfo: true` in the config of WebpackDevServer,but it didn't work.

**Comment by weblogixx** [comment]
Hi @madwiki,

the generated warnings are mainly caused by the eslint plugin. To disable them, just remove the eslint-loader from cfg/defaults.js (preloader section).

The warnings from the dev server cannot be removed as far as I know, but I may be wrong at this point.
