### ISSUE TITLE
Including process.env values in src/config object

### ISSUE THREAD

**Issue by sinisterra** [newtriks/generator-react-webpack#207]
Hi there,

Just wondering: is it possible to include process.env properties into the src/config object? If so, how can I do it? Thanks a lot!

Keep up the good work, this generator is amazing!

**Comment by weblogixx** [comment]
Hi @sinisterra,

indeed it seems to be possible. Just add your wanted variables via webpacks define plugin (you can see an example in cfg/dist.js for this). You are able to use set variables in the frontend via process.env.VARNAME.

Seems to work in frontend and dist versions.

Hope this helps.

**Comment by weblogixx** [comment]
Closing this as there was no feedback for 3 weeks. Please feel free to reopen this ticket if your problem still persists.
