### ISSUE TITLE
why the cpu is very high

### ISSUE THREAD

**Issue by abnerCrack** [newtriks/generator-react-webpack#209]
hey:)
I run the program,The CPU has been high.
![22d3c9bf-40da-41ba-a654-638e77dd0e85](https://cloud.githubusercontent.com/assets/8336662/14852210/8818cdd6-0cb7-11e6-9bec-3ebb09566773.png)
how to fix this problem

**Comment by lsfcode** [comment]
Well , I think this is node's problem, and i have another problem ,can you help me fix this? i have submit a issue ,the number is 210.

**Comment by weblogixx** [comment]
Hi @abnerCrack,

webpack itself is a bit performance hungry, depending on the used system. It mainly depends on the plugins you are inserting. If you add d3 for example, performance for initial builds may drop rapidly. The more modules you are loading, the more time it will take.

That said, I use this generator (and the underlying template) with various systems (MacBook Pro 2009 with Core 2 Duo, current MacMini, various Windows and Linux based machines) on a daily basis and do not suffer any performance issues. SSDs help a bit here ;)

That said, I cannot think of anything we could do to make performance that better. New Webpack and Node versions may help here, but they are currently beta.

**Comment by abnerCrack** [comment]
Thank you for your answer,I try to change the higher version of the node,its better now.
