### ISSUE TITLE
When I perform the command $sudo yo react-webpack ,the npm error is show,do you know why? in Mac,i'm very worry!helpme

### ISSUE THREAD

**Issue by lsfcode** [newtriks/generator-react-webpack#210]
![-1](https://cloud.githubusercontent.com/assets/12317258/14878809/7c725e24-0d58-11e6-9204-47defce6da7b.jpg)

**Comment by weblogixx** [comment]
This seems to be a problem with your filesystem permissions. This should only be a problem when installing node from the node website directly, as it will require sudo privileges every time you install something globally.

I would recommend that you take a look at nvm (https://github.com/creationix/nvm). It makes managing node on mac and linux based systems dead simple and you will no longer need sudo privileges for installing packages globally. Also you will be able to install several node versions on your system.

**Comment by lsfcode** [comment]
@weblogixx   i should use which version of Node.js?

**Comment by weblogixx** [comment]
You may use whatever you like. The generator itself required node v4.0 at the minimum. However, I use it with 5.x on a regular basis. node 6.x will also offer a nice performance boost, however, I have not tried it yet (I heard that you have to recompile many native modules, so a simple switch does not seem to be possible).

Just try out the latest 5.x release by using

```
nvm install 5 # will install the latest 5.x release
nvm use 5 # will set the downloaded release as default
npm update -g # will update npm to latest
npm install -g yo generator-react-webpack ... # will install the generator globally
```

**Comment by lsfcode** [comment]
@weblogixx  thank you for answer me.Now I use n to the version of the node management.and my node version is 5.10.1  .   i am in China.now i am trying to install react-webpack.it's to0 difficult to me .
but thank you very much!

**Comment by weblogixx** [comment]
Hi,

glad I could help. You say it is too difficult to use. Could you tell me where you have problems with?

**Comment by lsfcode** [comment]
when I use yoman to install react-webpack, he will quote a wrong. Install other when there is no problem.
my node's version is 5.10.1 ,npm's version is 3.8.7.    
![-1](https://cloud.githubusercontent.com/assets/12317258/14907267/b21b2290-0df8-11e6-8cca-7f444cb5ff5f.jpg)

**Comment by lsfcode** [comment]
@weblogixx when I use yoman to install react-webpack, he will quote a wrong. Install other when there is no problem.
my node's version is 5.10.1 ,npm's version is 3.8.7.    
![-1](https://cloud.githubusercontent.com/assets/12317258/14907267/b21b2290-0df8-11e6-8cca-7f444cb5ff5f.jpg)

**Comment by weblogixx** [comment]
Hi,

I do not see any errors here. The sass loader (and maybe other plugins, too) will try to compile some binary packages during installation. This is needed to speed them up (e.g. for autowatching, which hooks itself into the filesystem via fsevents).

We are currently not using jade, it seems it may be a child dependency of the sass-loader. But this may be solved with the latest version of those tools.

You may run the command ```npm outdated```. Maybe there is a new version of sass-loader that you could install.

**Comment by lsfcode** [comment]
@weblogixx  I think this is the reason of the 'wall'. Because this is China!
But thanks very much!

**Comment by weblogixx** [comment]
You are welcome. Feel free to open new issues when problems arise.
