### ISSUE TITLE
Lost connection to webpack-dev-server.

### ISSUE THREAD

**Issue by x007xyz** [newtriks/generator-react-webpack#212]
The following error occurs:
`
E:\02-Study\gallery-by-react\node_modules\sockjs\lib\trans-websocket.js:157
      return this.session.close(6000, 'No response from heartbeat');
                         ^

TypeError: Cannot read property 'close' of null
    at WebSocketReceiver.heartbeat_timeout (E:\02-Study\gallery-by-react\node_modules\sockjs\lib\trans-websocket.js:157:
26)
    at null._onTimeout (E:\02-Study\gallery-by-react\node_modules\sockjs\lib\trans-websocket.js:75:24)
    at Timer.listOnTimeout (timers.js:92:15)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chenzx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\n
pm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! galleryByReact@0.0.1 start: `node server.js --env=dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the galleryByReact@0.0.1 start script 'node server.js --env=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the galleryByReact package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --env=dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs galleryByReact
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls galleryByReact
npm ERR! There is likely additional logging output above.
`

**Comment by weblogixx** [comment]
Hi @x007xyz,

could you provide some more information like:

- Generator Version
- Operating System
- Maybe link to the repo that has the error?

With this information alone there is unfortunately nothing I can say...

**Comment by x007xyz** [comment]
Hi @weblogixx ,

- Generator-react-webpack@3.3.0;
- Operating System is win10;
- Now it's normal before but there is an error,I don't know why

Thanks for your reply

**Comment by x007xyz** [comment]
npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\chenzx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.8.7
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle galleryByReact@0.0.1~prestart: galleryByReact@0.0.1
6 silly lifecycle galleryByReact@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle galleryByReact@0.0.1~start: galleryByReact@0.0.1
8 verbose lifecycle galleryByReact@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle galleryByReact@0.0.1~start: PATH: C:\Users\chenzx\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\02-Study\gallery-by-react\node_modules\.bin;C:\Program Files\nodejs;c:\program files\graphicsmagick-1.3.23-q8;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Acer\abFiles\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files\Java\jdk1.7.0_79\bin;C:\Program Files (x86)\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Calibre2\;C:\Program Files\nodejs\;C:\Program Files\phantomjs-2.1.1-windows\bin;C:\Ruby22-x64\bin;C:\Program Files\nodejs\node.exe;C:\Python27;C:\Users\chenzx\AppData\Roaming\npm
10 verbose lifecycle galleryByReact@0.0.1~start: CWD: E:\02-Study\gallery-by-react
11 silly lifecycle galleryByReact@0.0.1~start: Args: [ '/d /s /c', 'node server.js --env=dev' ]
12 silly lifecycle galleryByReact@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle galleryByReact@0.0.1~start: Failed to exec start script
14 verbose stack Error: galleryByReact@0.0.1 start: `node server.js --env=dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\chenzx\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\chenzx\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid galleryByReact@0.0.1
16 verbose cwd E:\02-Study\gallery-by-react
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chenzx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.4.3
20 error npm  v3.8.7
21 error code ELIFECYCLE
22 error galleryByReact@0.0.1 start: `node server.js --env=dev`
22 error Exit status 1
23 error Failed at the galleryByReact@0.0.1 start script 'node server.js --env=dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the galleryByReact package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js --env=dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs galleryByReact
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls galleryByReact
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by weblogixx** [comment]
Hi @x007xyz,

could you please provide a link to the repo if this is possible? Unfortunately I cannot say anything about this issue without seeing the code (included modules etc). I have never seen this kind of error before with the stuff I am using the generator.

**Comment by x007xyz** [comment]
Hi @weblogixx ,

I know why wrong.When I use Chrome(version 47.0.2526.106 m),it is go wrong.But I use other browser,it is OK.So I uninstall Chrome(version 47.0.2526.106 m) and then install the latest version,it is all right.the generator is good.

Thanks for you reply.
