### ISSUE TITLE
[Question] config module

### ISSUE THREAD

**Issue by alexsotocx** [newtriks/generator-react-webpack#214]
I want to know how it works, when you are in a component and import the config
```javascript
let config = require('config'); 
```
There is no module **config** or something, how does it recognise where to search? and how does it merge the other config from the config folder?

**Comment by alexsotocx** [comment]
Never mind... I found it :D Nice way to do the things!

**Comment by weblogixx** [comment]
;). You are welcome

**Comment by v-komarov-parc** [comment]
The quastion still actual.
Can anybody explain how it works?
