### ISSUE TITLE
arrow functions & rest spread syntax is works on OS X, but comes to error on Windows

### ISSUE THREAD

**Issue by leftjs** [newtriks/generator-react-webpack#219]
there are code and babel config
.babelrc:
``` bash
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ], 
  "plugins":["transform-runtime","transform-object-rest-spread"]
}
```
./cfg/dev.js: 
``` javascript
config.module.loaders.push({
  test: /\.(js|jsx)$/,
  loader: 'react-hot!babel-loader',
  include: [].concat(
    config.additionalPaths,
    [ path.join(__dirname, '/../src') ]
  )
});
```

I think of these configs are corrent, just don't know that how windows run it and why it comes to errors, there is my screenshot:
![error](http://ww2.sinaimg.cn/large/71ae9b51jw1f3xpjbqq2vj20mk0waag4.jpg)
please tell me how to fix it, thanks

**Comment by leftjs** [comment]
ps. I use the generator with redux, [https://github.com/stylesuxx/generator-react-webpack-redux](redux)

**Comment by weblogixx** [comment]
Hi @leftjs,

I havent really tried the redux generator (it is maintained separately). However, arrow functions and rest/spread should work out of the box, even with the current generator. I am also using it in base and alt.js with no changes in the config. Maybe @stylesuxx is able to help here?

**Comment by weblogixx** [comment]
@leftjs: Closing this as it seems to have to do with a foreign project and there are no news for one month. Please feel open to report the bug on the redux version of the generator (or reopen an issue if it seems like this generator is the error source).
