### ISSUE TITLE
when i using `yo react-webpack`,there are no files generatored in my project.

### ISSUE THREAD

**Issue by summerGreenTea** [newtriks/generator-react-webpack#220]
there were three questions show when i used command `yo react-webpack`:
Please choose you application name 
which style language do you want to use
enable postcsss

ended, no thing happened.  It's so strange.

**Comment by weblogixx** [comment]
Hi @summerGreenTea,

I seem to have pushed a broken package to npm. Will update in a couple of minutes. Please stand by :(

**Comment by summerGreenTea** [comment]
@weblogixx    thx !  I installed again. And now, it's working;

**Comment by weblogixx** [comment]
Sorry for the problems. Tests ran through, I did not test it live. Will have a closer look at the problems and eventually rerelease later this week.
