### ISSUE TITLE
component generator appending "Component" to component name

### ISSUE THREAD

**Issue by yipcma** [newtriks/generator-react-webpack#223]
is this desired?

**Comment by weblogixx** [comment]
Yes, it is. This will get removed in the next major version

**Comment by yipcma** [comment]
look forward to the update. appr. when would that come out? also would there be a yo command to remove a component and its associated styl and test?

**Comment by weblogixx** [comment]
Hi @yipcma,

We are currently working on the underlying template first. If possible I want to release it with support for webpack-2. So basically I cannot say it. Maybe two weeks, maybe two months. 

The current version is pretty stable, but we will have some changes for newly generated projects in the pipeline:

- more help for newly generated projects (maybe a wiki)
- Styling will not be in its own styles folder, but in the components one. 
- we will (propably) use css modules. Support for this is currently available in the 2-alpha version
- unittests will run with airbnbs enzyme

All that will be backwards compatible wirh projects generated with version  3.x of the generator. New features are currently planed to be released with the new major.
