### ISSUE TITLE
Node server will not start

### ISSUE THREAD

**Issue by kcgunn** [newtriks/generator-react-webpack#231]
Getting Errors upon trying to get up and running with this Generator. I am using node v4.4.3 and npm v3.9.3, getting a Exit Status 1 with no real other error messages when running npm start and also npm run serve. Says Failed at the serve script 'node server.js --env=dev'. I am running on Windows 7 professional SP1, windows_NT 6.1.7601. Any guidance is appreciated.

**Comment by kcgunn** [comment]
I'm guessing this is a Windows issue...code works fine on my MBP

**Comment by weblogixx** [comment]
Hi @kcgunn,

I am currently running the generator on Win 7 with node 4.4, there are no problems that I can see here. Will test it with 4.2 tomorrow.

**Comment by weblogixx** [comment]
@kcgunn, I do not get any problems on different machines (and operating systems). There is no news for about a month, so I will close this for now. However, feel free to open another issue if such a problem still arises.
