### ISSUE TITLE
Watch Flag for Unit Tests

### ISSUE THREAD

**Issue by JimTheMan** [newtriks/generator-react-webpack#234]
I like to do "dual shell development" that is basically TDD with one shell running tests with a watch flag and one shell running npm start. 

It would be nice to have a task for unit tests that watches files:
`npm test:watch`

**Comment by weblogixx** [comment]
Hi Jim,

this task already exists, even the name is the same. Just use npm run test:watch to use it.

**Comment by JimTheMan** [comment]
ah true. Definitely should be in the docs :)
