### ISSUE TITLE
E2e Tests with Protractor

### ISSUE THREAD

**Issue by JimTheMan** [newtriks/generator-react-webpack#235]
It is even possible to use protractor in React projects? If so, this gives an extra layer of testing to fill in any cracks that may be missed by unit tests. :)

**Comment by weblogixx** [comment]
Hi Jim,

yes it is possible. Personally I have used webdriver.io instead of protractor, but both need to just be set up as with any other project. 

However, we will not include it into the base generator, as it should be as slim as possible.

**Comment by JimTheMan** [comment]
ok good to know. thanks.
