### ISSUE TITLE
Can't Find app.js When Deployed

### ISSUE THREAD

**Issue by JimTheMan** [newtriks/generator-react-webpack#236]
I make a dist build by running this:

`npm run dist`

I then push that to master. Then I push it to my gh-pages branch on github like this:

`git subtree push --prefix dist/ origin gh-pages`

I can see all the files in the gh-pages root as they should be:
https://github.com/JimTheMan/React-Webpack-Project/tree/gh-pages
![screen shot 2016-06-12 at 11 59 33 am](https://cloud.githubusercontent.com/assets/5354163/15992197/5fc7e05e-3095-11e6-806b-748422f7ae9a.png)

But then when I navigate to the site it just shows the "can't find app.js" error. :(
http://jimtheman.github.io/React-Webpack-Project/
![screen shot 2016-06-12 at 12 02 22 pm](https://cloud.githubusercontent.com/assets/5354163/15992207/99e2693a-3095-11e6-8629-4fba1445b63d.png)

**Comment by JimTheMan** [comment]
I seemed to have been able to fix the build script by going into cfg/base.js and changed line 18:

` path: path.join(__dirname, '/../dist/assets'),`

to this (extra slash on the end of assets):

` path: path.join(__dirname, '/../dist/assets/'),`


Only then does it work. But this is a strange thing for it to happen to only me. Surely I am not the only one deploying my files. So then why is this happening? Can we add the / to master, or am I doing something wrong that it doesn't work out of the box?

**Comment by weblogixx** [comment]
Hi @JimTheMan,

seems to be related to https://github.com/newtriks/generator-react-webpack/issues/233.
I will have a look at this and eventually fix it in one of the next versions.

**Comment by JimTheMan** [comment]
Hmm. It seems like I am getting the error again even with the extra slash. This in an incredibly serious issue, and I'm amazing that other people aren't upset about this since this generator can never be used on anything more than a throw-away project if you can't publish a finished project. 

If no one is concerned that you can't deploy a project then I guess it's time to look for a new React generator. : /

**Comment by JimTheMan** [comment]
Had to also take out the / from the path in index.html

Changed

`<script type="text/javascript" src="/assets/app.js"></script>`

to

`<script type="text/javascript" src="assets/app.js"></script>`

**Comment by weblogixx** [comment]
Hi Jim,

just received your original comment. There are some things wrong with the way you think creating dist versions work. You should never use a webpack dev server for creating live pages. 

All that matters is the dist version of app.js. Modt people do not even use the included app.js, but upload their projects for usage with apache, lighthttp or even cdns. So it is not as big of a bummer that you think it is. 

Just setting the path so it works for your setup is a easy step for current usage. Think about it: There are people using it on their primary domain, subdomain, cdn or a folder. There is no setup that fits everyone. Hope this info helps.

**Comment by WillTheSun** [comment]
Hey Jim,

Thanks a lot for posting this. I had the same problem when trying to deploy to GitHub pages and your edits worked perfectly.
