### ISSUE TITLE
Browser keeps loading "old" version of js files

### ISSUE THREAD

**Issue by Trickass** [newtriks/generator-react-webpack#240]
When running `npm start`, a browser is launched to `http://localhost:8000/webpack-dev-server/` (which is expected).

Then, when changing anything in code, for example in the `Main.js` file, nothing happens in the browser.
Worse even, when refreshing the browser window, the changes made to the source code are not reflected at all.

Is there anything else I need to do to get this working? Extra watch/build commands to run?

Thank you

**Comment by weblogixx** [comment]
Hi @Trickass,

which version of the generator do you use? I have expected something like this too, but only with the current beta (where it is fixed, too). Make sure your webpack configuration does not have a key of ```cache: true``` set.

In the current stable, watch files in the cfg directory, in the beta it is located in config/webpack.

**Comment by Trickass** [comment]
I've only installed the generator today via `npm install -g generator-react-webpack`.
It seems to be using version 3.3.2.

I've tried setting the `cache: false` as it was indeed on `true` in the dev config, but seems to make no difference.

**Comment by weblogixx** [comment]
Hi @Trickass,

I just tested it with a newly generated project (even uninstalling the generator and reinstalling it again) and did not have any problems. Could you give me some more information?

- Operating System
- Version of node you run on (and install type, e.g. native or nvm/nvwm)
- Version of npm

Also, altering the the cache key is not required (at least under osx), it does not have an impact.
Which browser did you try to open the page with? Does it have any errors in the console?

A valid console after a request should look like this:

![running](https://cloud.githubusercontent.com/assets/757613/16118599/2764d03c-33d8-11e6-94de-13d80191d81f.png)

**Comment by Trickass** [comment]
I'm running Windows 10 with node (native, i think?) v6.2.1 and npm version 3.9.3
Opened the page using Chrome.

Running (`npm start`) provides following result:

![capture](https://cloud.githubusercontent.com/assets/1467263/16118752/d1b58b8a-33d8-11e6-90cf-f2b04e430714.PNG)

**Comment by weblogixx** [comment]
Seems fine from a setup side of things. You do not need to run anything else, just a regular npm start.
Unfortunately I do not have a windows 10 vm to test it, will take some time. There are no problems on Windows 7 and I did not get any reports that there are known problems with Win10.

I will check it, but it will take some time. Did you get any output in your command line when altering main.js? Could you please paste the output of your ```npm start``` command (including changed output after you changed Main.js)? Maybe we can see something wrong there.

When the server is started and you change a file in the src directory, it should add a line like this:

```
webpack: bundle is now VALID.
// EDIT!!! THIS IS FROM THE PREVIOUS RUN WHEN WEBPACK IS READY
// PLEASE SAVE THE FILE IN YOUR EDITOR NOW, e.g. by adding "test" somewhere...
// EXPECTED OUTPUT:
webpack: bundle is now INVALID.
Hash: d624dc1b83867b5f354f // WILL BE DIFFERENT ON YOUR SYSTEM
Version: webpack 1.13.1 // MAY BE DIFFERENT ON YOUR SYSTEM
Time: 489ms
 Asset     Size  Chunks       Chunk Names
app.js  xxxx MB       0       main
chunk    {0} app.js (main) xxxx MB
.... // LONG LIST OF DEPENDENCIES
webpack: bundle is now VALID. // After saving, this should be the last line again!
```

**Comment by Trickass** [comment]
Nothing is added there, so I guess there's something going wrong on that level already...

Output from `npm start` command:

>npm start

>\>test@0.0.1 start C:\Projects (Personal)\TEST
>\>node server.js --env=dev

>Listening at localhost:8000
>Opening your system browser...
>webpack: wait until bundle finished: /assets/app.js
>Hash: 4db2d6e5c14459d227d4
>Version: webpack 1.13.1
>Time: 4028ms
>                               Asset     Size  Chunks             Chunk Names
>42092f929161dae9c08a21bfb46ece4d.png  13.5 kB          [emitted]
>                              app.js  2.62 MB       0  [emitted]  main
>chunk    {0} app.js (main) 930 kB [rendered]
>    [0] multi main 52 bytes {0} [built]
>    [1] (webpack)-dev-server/client?http://127.0.0.1:8000 2.67 kB {0} [built]
>    [2] ./~/url/url.js 22.3 kB {0} [built]
>...
>  [299] ./~/react-hot-loader/isReactClassish.js 801 bytes {0} [built]
>  [300] ./~/react-hot-loader/isReactElementish.js 288 bytes {0} [built]
>webpack: bundle is now VALID.`

**Comment by weblogixx** [comment]
In this case it does not seem to be a problem with the generator, but maybe with the webpack dev server. There are some known issues from windows 8/10 users that I found here: https://github.com/webpack/webpack-dev-server/issues/155.

For example, if you got any special chars in your absolute path you seem to be screwed...
One user suggested to use git bash for windows where the problem (possibly cmd.exe related?) does not come to pass.

**Comment by Trickass** [comment]
I tried running it in git bash, but got another error - which I get in cmd now as well, even after re-running the generator.
I really don't want to give up, but I'm getting close :D ;)

![capture](https://cloud.githubusercontent.com/assets/1467263/16120273/2ed706a8-33df-11e6-830a-4b532ce9d22d.PNG)

```
   [72] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [73] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [74] ./~/webpack/hot/only-dev-server.js 2.25 kB {0} [built]
   [75] ./~/webpack/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/index.js
Module parse failed: C:\Projects (Personal)\test\src\index.js Unexpected token (7:16)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:16)
    at Parser.pp.raise (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.unexpected (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:1490:8)
    at Parser.pp.parseExprAtom (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:207:17)
    at Parser.pp.parseExprOps (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:112:19)
    at Parser.pp.parseExprList (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:660:23)
    at Parser.pp.parseSubscripts (C:\Projects (Personal)\TEST\node_modules\acorn\dist\acorn.js:252:29)
 @ multi main
webpack: bundle is now VALID.
```

**Comment by weblogixx** [comment]
Do you have any special chars in your path? If you have, try to move to project to a main folder (e.g. c:) directly and use folder naming without special chars (e.g. whitespaces, slashes...). Have a look if it works on this folder (like, move it to c:\test). Maybe this may help.

**Comment by Trickass** [comment]
I retried from "C:\Projects\Test", so no special chars there.

What I **did** notice just now, when re-running the generator, is this:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```

Could it be that a windows alternative for this should be installed instead?

**Comment by Trickass** [comment]
All right!
I've found the issue!

On https://webpack.github.io/docs/troubleshooting.html I found this:

> webpack expects absolute paths for many config options. __dirname + "/app/folder" is wrong, because windows uses \ as path separator. This breaks some stuff.
> 
> Use the correct separators. I.e. path.resolve(__dirname, "app/folder") or path.join(__dirname, "app", "folder").

I changed line 23 in cfg/base.js to `contentBase: '.\\src\\'`, which seems to do the trick!!

**Comment by weblogixx** [comment]
Hi,

I will add a cross system fix for this. Should be easy to use /on unix(likes) and \ for win. Thank you for the hint!

**Comment by Trickass** [comment]
No problem. Thanks for your help as well.

**Comment by weblogixx** [comment]
Hi @Trickass,

those are located in a dependency [here](https://github.com/weblogixx/react-webpack-template)
