### ISSUE TITLE
Support Generating CSS-File in Component Directory

### ISSUE THREAD

**Issue by sthzg** [newtriks/generator-react-webpack#242]
Would you consider adding an option to the component sub-generator that would create the style-file (css, scss, less, ...) inside the component directory itself rather than the `.src/style` directory? 

E.g. `yo react-webpack:component my/namespaced/components/name --stylesincompdir`

**Comment by weblogixx** [comment]
This will be the standard in version 4 (testable via the npm beta tag). Older projects will still add to the styles directory for backwards compatibility.

**Comment by sthzg** [comment]
Oh great, I was still looking more into the new template project instead of the new generator as a whole. Thanks for clarifying.
