### ISSUE TITLE
npm install @beta doesn't include utils directory

### ISSUE THREAD

**Issue by sthzg** [newtriks/generator-react-webpack#245]
```
$ npm install generator-react-webpack@beta
$ tree node_modules/generator-react-webpack
node_modules/generator-react-webpack
├── CHANGELOG.md
├── LICENSE
├── generators
│   ├── ...
└── package.json

12 directories, 23 files
```
Looking at the `package.json` and browsing the [npm docs regarding the `files`](https://docs.npmjs.com/files/package.json#files) attribute my first guess would be that `utils` should be part of that list.

**Comment by weblogixx** [comment]
@sthzg,

thanks for the feedback, just updated the beta tag with a (hopefully) running version and files included :)
