### ISSUE TITLE
npm start Error : module.js:327

### ISSUE THREAD

**Issue by daisyHawen** [newtriks/generator-react-webpack#251]
After I yo react-webpack React-gallery , I use the "npm start" to test it ,it throws an error.
Error: Cannot find module 'core-js/fn/object/assign'
Please tell me why?
the specific log is as follows:

`
$ npm start
> no@0.0.1 start E:\react\React-gallery
> node server.js --env=dev

module.js:327
    throw err;
    ^

Error: Cannot find module 'core-js/fn/object/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\react\React-gallery\server.js:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\A                                                                 ppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! no@0.0.1 start: `node server.js --env=dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the no@0.0.1 start script 'node server.js --env=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the no package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --env=dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs no
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls no
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\react\React-gallery\npm-debug.log
`

**Comment by daisyHawen** [comment]
After I reuse the command : yo react-webpack React-gallery
I have done this problems

**Comment by weblogixx** [comment]
Hi @daisyHawen,

does that mean the problem disappeared? This may sometimes be a problem with the npm package download not downloading all packages correctly. In this case, a simple ```npm install``` should install the missing packages. We see this problem often when users are behind the great wall of china....
