### ISSUE TITLE
V4 -- Generate styleName attribute only when appropriate

### ISSUE THREAD

**Issue by sthzg** [newtriks/generator-react-webpack#255]
Currently the `styleName` attribute is added even when

- `cssmodules` is set to false in `.yo-rc.json`
- the component is generated with `--nostyle`

**Comment by sthzg** [comment]
@weblogixx I've poked around a little and think that there are a few logical branches to support. `+` and `-` indicate the current support:

```
1) nostyle
    + no style import
    + no cssmodule annotation
    - no styleName attribute
    + no style file

2) styles, but cssmodules=false
    - style import/require, but no assignment to variable (=> eslint unused)
    - no cssmodule annotation
    - no styleName attribute
    - stylefile with naming scheme of <component>.<styletype> (e.g. foo.less)

3) styles, with cssmodules
    + style import with assignment to variable
    + cssmodule annotation
    + styleName attribute
    + style file with naming scheme of <component>.cssmodule.<styletype>
    
```

I think there needs to be a new flag added to the settings that can be used to branch between 2) and 3), for example:

```js
settings.useCssModules = this.config.get('cssmodules') || false;
```

And then there is the issue of implementation. 

It can be packed all into one template file (`Base.js`, `Stateless.js`). Pros: it remains in one file, Cons: ugly if-elses in the templates and no precise newline control. That means, to unify output it probably would have to be piped through some beautifier.

Another way would be a) working with multiple templates (`BaseNoStyle.js`, `BaseStyles.js`, `BaseCssModules.js`) or b) working with ejs-includes. Ejs-includes may be more DRY by the cost of readability, multiple templates aren't DRY and changes need to be reflected in a few files (however, I think this can be quite easily resolved with good tests, and base templates aren't subject to frequent changes.)

**Comment by weblogixx** [comment]
Hi @sthzg,

will have to think about it. Basically, if we want to use this, we should really create some simple default components with a maximum of one if statement (e.g. stateless, statefull, with cssmodules, without it...). Should be relatively easy to test, because the test suite can already handle different flags in its current incarnation.

**Comment by sthzg** [comment]
@weblogixx should I look into it and provide a PR or would you prefer keeping it in the queue for a bit until there is a final decision for it?

**Comment by weblogixx** [comment]
Hey @sthzg,

that would be really nice. There is too much in the pipeline for me alone currently :(. I think multiple base files would be better for this task. However, it could get complicated because we are also supporting the v3 version currently.

**Comment by sthzg** [comment]
@weblogixx ah, interesting. I was under the impression that the current `/v3/**` and `/v4/**` template structures would handle that separation. I will start implementing a solution using multiple base files and come back here when either there is sth. to show or to discuss if some blockers were too big to simply go on.

**Comment by weblogixx** [comment]
Hi @sthzg,

yes, indeed they are. However, version 3 only knows about regular and stateless components, not cssmodule ones. Thats the reason I was saying it :)

**Comment by sthzg** [comment]
@weblogixx I've just pushed an initial commit to coordinate the direction with you. https://github.com/sthzg/generator-react-webpack/commit/d08625612bd967b9fb26b5f1431ba96eecec8200

As noted in the commit message, first manual tests in v3 and v4 are working and, if the direction is okay, I'd work on updating the automated tests next, and then start detailed manual tests as well as probably iterating a bit over the code.

- [Updated index.js](
https://github.com/sthzg/generator-react-webpack/blob/d08625612bd967b9fb26b5f1431ba96eecec8200/generators/component/index.js)
- [Updated v3 template dir](https://github.com/sthzg/generator-react-webpack/tree/d08625612bd967b9fb26b5f1431ba96eecec8200/generators/component/templates/3/components)
- [Updated v4 template dir](https://github.com/sthzg/generator-react-webpack/tree/d08625612bd967b9fb26b5f1431ba96eecec8200/generators/component/templates/4/components)

At first sight, it was funny to see that many different files, but to be honest I like working with them much more than with the ugly EJS conditions inside the templates (or a totally over-engineered AST processing for this purpose). I am currently of the opinion, that this is one case where verbosity actually has advantages over abstractions (those files will hardly ever change and if they do, it's easy to keep track of).

**Comment by sthzg** [comment]
(Manual) Tests

**V3**
- [ ] --nostyle stateful validates and tests
- [ ] --nostyle stateless validates and tests
- [ ] with style stateful validates and tests
- [ ] with style stateless validates and tests

**V4**
- [ ] --nostyle stateful validates and tests
- [ ] --nostyle stateless validates and tests
- [ ] with style stateful validates and tests
- [ ] with style stateless validates and tests
- [ ] with cssmodules stateful validates and tests
- [ ] with cssmodules stateless validates and tests

**Comment by weblogixx** [comment]
Pure genius 👍 . Looks really sweet and nicely implemented. Will have a deeper look at it today.

**Comment by sthzg** [comment]
I've now squashed the branch into one commit so that it is easier to review and if everything is fine ready to become a PR.

**Comment by weblogixx** [comment]
Just looked into it, hopefully awaiting your pr 👍

**Comment by sthzg** [comment]
Ready in https://github.com/newtriks/generator-react-webpack/pull/268
