### ISSUE TITLE
'npm run dist' erro !  

### ISSUE THREAD

**Issue by zhouyu1993** [newtriks/generator-react-webpack#257]
+ 1 hidden modules  ERROR in Cannot find module '../scope'

what is '../scope' ?

And how can I 'webpack' ?

**Comment by weblogixx** [comment]
Hi @zhouyu1993,

sometimes there are problems when using npm behind the wall. In this case, it usually helps to just run npm install again to fetch any missing packages. You do not need to run webpack by itself, ```scope``` is a folder inside the webpack dependency that was not correctly fetched in your setup.

**Comment by weblogixx** [comment]
Hi @zhouyu1993,

there was no response for 20 days now, so I will handle this issue as resolved. Feel free to reopen it if your problem still persists.
