### ISSUE TITLE
Remove Grunt default install and add as an option

### ISSUE THREAD

**Issue by newtriks** [newtriks/generator-react-webpack#26]
Have Grunt installed as an option during running of Yeoman.

**Comment by jasongroulx** [comment]
Could Gulp be installed as an option?

**Comment by newtriks** [comment]
@jasongroulx that's the way I'm thinking this could go, have Grunt, Gulp, etc optional.

**Comment by frostney** [comment]
Would you mind if I took a crack at it? I would like to see a Gulp option and a "No task runners" option.

**Comment by newtriks** [comment]
Of course, that would be appreciate thanks!

**Comment by dperetti** [comment]
+1 for Gulp !

**Comment by sgentile** [comment]
I'd prefer neither, to me the benefit of webpack is not having to use grunt/gulp ... why is it even needed ?

https://www.youtube.com/watch?v=VkTCL6Nqm6Y

**Comment by newtriks** [comment]
@sgentile I hear ya and I pretty much cover most of my needs without Grunt or Gulp, however, there is still a goof amount of traction with those libs so an option at least should and could easily be maintained.

**Comment by IngenieroLata** [comment]
What have happened with this? I like gulp more tan grunt so could be awesome include that option

**Comment by weblogixx** [comment]
We have opted to remove task runners altogether in the next major release, because everything the generator does can also be done via npm scripts.
