### ISSUE TITLE
Content flash?

### ISSUE THREAD

**Issue by pikeas** [newtriks/generator-react-webpack#30]
I'm using this generator to explore React. I'm new to both yeoman and React, so let me know if I can add more detail or if I should move this issue elsewhere.

With a clean install (`yo react-webpack; bower install; npm install; grunt serve`), there's an unstyled content flash when opening up the app. Is this an issue with the generator?

**Comment by KingScooty** [comment]
+1 - Chrome 40 on Yosemite. 

Getting a flash of the 'JS isn't enabled message' before the everything loads in.

**Comment by ColCh** [comment]
It's needed to make serverside rendering and extract CSS into separate file: see [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin). Yup that's very important thing on production builds, but do we really need to refuse CSS Hot Load in favor of FOUC fix?

**Comment by newtriks** [comment]
@ColCh agreed. I think this maybe out of scope of the generator but welcome comments here or links for people to overcome this issue on production builds? Gonna close for now unless someone has a better solution that doesn't compromise dev builds....
