### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by ColCh** [newtriks/generator-react-webpack#31]
Create component with invalid JS var name:
```
$ yo react-webpack:component App-description
```

and inside component jsx file:
```

var App-description = React.createClass({
  render: function () {
    return (
        <div>
          <p>Content for App-description</p>
        </div>
      );
  }
});
```

Yep `App-description` is invalid variable name. 

So may be throw some errors while creating component files?

**Comment by ColCh** [comment]
I think right behaviour must be throwing an exception for wrong variable identifiers

**Comment by weblogixx** [comment]
The new version of the generator was updated to include a fix for this issue. However I do not think that we need to port it back to the 1.0 version.
