### ISSUE TITLE
V4 -- Cssmodules decorator in component

### ISSUE THREAD

**Issue by stylesuxx** [newtriks/generator-react-webpack#325]
From [here](https://github.com/stylesuxx/generator-react-webpack-redux/issues/62) the template seems to be using decorators in the v4.0.1-1 branch => https://github.com/react-webpack-generators/generator-react-webpack/blob/v4.0.1-1/generators/component/templates/4/components/Base.js

I think the master is more up to date regarding those templates, or am I missing something?

**Comment by sthzg** [comment]
@stylesuxx I refactored that when I was rebuilding the base templates for the different components. Main reasons were to get rid of conditionals in the ejs templates and decorators in general as they are still only a draft and haven't made their way into the standard yet (has that changed in the meantime?).

**Comment by stylesuxx** [comment]
Yes, sorry. I meant to close that down yesterday. It was late and I managed to confuse myself.
My gen was using the latest v4 tag, but the base for the next v4 is master, so I switched that and everything is OK now.

**Comment by sthzg** [comment]
:smile: glad to hear.
