### ISSUE TITLE
Can Bootstrap be provided as an option?

### ISSUE THREAD

**Issue by polluxus** [newtriks/generator-react-webpack#47]
Thank author. I like  the react-webpack very much. It's awesome. However, it took me quite a long time to get bootstrap into my project.   Is it possible to have bootstrap loaded as an option, like the way react-router is provided?  Or, is there an easy way to load bootstrap? thanks

**Comment by newtriks** [comment]
Hey @polluxus thank you :) In regards to integrating BS, I am personally not so keen. However, a well documented page could be created for this repos wiki on how to do it?
