### ISSUE TITLE
Loss of .jsx extension

### ISSUE THREAD

**Issue by cedricss** [newtriks/generator-react-webpack#49]
Looks like #38 merged pull request has moved reactSuffix from `.jsx` to `.js`, breaking some user build rules or code editor conf based on the extension.
 
Example: `scripts/component/main.js` is still a JSX file but with the `.js` extension.

Any particular reason for this change? /cc @andrewliebchen

**Comment by newtriks** [comment]
It's a hot topic and I welcome thoughts, maybe this should be configurable and therefore an option when running Yeoman....?

https://github.com/facebook/react/issues/832
https://github.com/kriasoft/react-starter-kit/issues/52#issuecomment-72844613

**Comment by andrewliebchen** [comment]
Making it an option is a nice idea!

**Comment by cedricss** [comment]
Oh indeed, it looks clear that Facebook is pushing forward the `.js` extension (see latest [reactjs conf videos](https://www.youtube.com/playlist?list=PLb0IAmt7-GS1cbw4qonlQztYV1TAW0sCr), or [their code example](https://github.com/facebook/react/tree/master/examples)).

And some code editor plugins are experimenting [other ways](https://github.com/orktes/atom-react/pull/29) to detect JSX file.

In the end, I'm in favor of keeping `.js` as the default and only option:
* to continue this convention adoption effort 
* to avoid confusing new react user with an extra subtle option

**Comment by newtriks** [comment]
> to avoid confusing new react user with an extra subtle option
@cedricss agreed. So, I will close this and stick with how it is for now but reopen if the consensus changes.
