### ISSUE TITLE
Hot loader not reloading on save

### ISSUE THREAD

**Issue by jonaswindey** [newtriks/generator-react-webpack#52]
When I save a JS(x) file or stylesheet, my webpack bundle gets rebuilt but the content doesn't change in the browser. I need to manually refresh the page.

I launch the server with the webpack-dev-server grunt task. Is there anything else I need to do to enable live reloading?

**Comment by hardchor** [comment]
You need to navigate to http://localhost:8000/webpack-dev-server/ (only found this out by reading through the Gruntfile)

**Comment by supnate** [comment]
To avoid webpack-dev-server in the url with hot-loader, add an entry in your webpack.config.js like below:
```js
entry: [
      'webpack-dev-server/client?http://127.0.0.1:8000',
      'webpack/hot/only-dev-server',
      './src/scripts/components/TestApp.js'
  ],
```

**Comment by andrewliebchen** [comment]
:+1: This was a great help. Not sure why hot reload only works at the Webpack dev server URL out of the box. Would prefer to hit the bare url to have hot reloading.
