### ISSUE TITLE
react-webpack:component asset path is not properly created...

### ISSUE THREAD

**Issue by dannymk** [newtriks/generator-react-webpack#54]
yo react-webpack:component Panels/Main
...
styles/Component
   create src/scripts/components/Panels/Main.js
   create test/spec/components/Panels/Main.js
   create src/styles/Panels/Main.sass
...

in components/Panels/Mail.js
...
require('../../styles/Main.sass');  //<--- this does not work
it should be
require('../../../styles/Panels/Main.sass');  //<--- works!

**Comment by ColCh** [comment]
Wow, nice feature request here

I think that it's better to make alises [in webpack config] to point in 'src/styles' dir
