### ISSUE TITLE
App doesn't start and aliases are broken (Alias PR)

### ISSUE THREAD

**Issue by framp** [newtriks/generator-react-webpack#63]
The alias PR #62  broke the generator. 

After generating the app nothing starts because of a missing comma on line 36 in `_webpack.dist.config.js`.

The default app is broken too because alias feature isn't working with `./src/styles` and the default App crashes.

It's working if I change it to:

    alias: {
      'styles': '../../../src/styles',
      'components': '../../../src/scripts/components/'
    }

but I hope there is a better way I still haven't figured out.

Error here:

    Module not found: Error: Cannot resolve 'file' or 'directory' /src/styles/normalize.css in /my-path/src/scripts/components
    @ ./src/scripts/components/MyNameApp.js 9:0-31

Awesome generator btw! 
Keep up the good work

**Comment by shunchu** [comment]
I'm experiencing the same issue. Thanks for filing this bug.

**Comment by nirarazi** [comment]
Same issue for me too

**Comment by joe5yellow** [comment]
I noticed that in `./scripts/components/yourApp.js`, there is
```
// CSS
require('./styles/normalize.css');
require('./styles/main.css');

var imageURL = require('../../images/yeoman.png');
```
I changed styles file paths(with that comma fix first) to 
```
// CSS
require('../../styles/normalize.css');
require('../../styles/main.css');
```
also fix the issue.

Will #66 be better?

**Comment by framp** [comment]
That was the original solution before #62, which introduced aliases.

The best solution would be to have an option on webpack to set the root path IMHO
