### ISSUE TITLE
npm install failed at building node-sass@1.2.3

### ISSUE THREAD

**Issue by joe5yellow** [newtriks/generator-react-webpack#67]
Error message:
```
`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zhaomin/repos/rr/node_modules/sass-loader/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhaomin/repos/rr/npm-debug.log
```

I think node-sass is only used in sass-loader which requires node-sass to play sass files.
I will try an upgrade of sass-loader from 0.3.1 to 0.4.0.

**Comment by joe5yellow** [comment]
```
> node-sass@2.0.1 install /Users/zhaomin/repos/rr/node_modules/sass-loader/node_modules/node-sass
> node scripts/install.js


> node-sass@2.0.1 postinstall /Users/zhaomin/repos/rr/node_modules/sass-loader/node_modules/node-sass
> node scripts/build.js

`darwin-x64-node-0.12` exists; testing
Binary is fine; exiting
sass-loader@0.4.0 node_modules/sass-loader
├── loader-utils@0.2.6 (json5@0.1.0, big.js@2.5.1)
├── sass-graph@1.0.3 (commander@2.6.0, lodash@2.4.1, glob@4.4.0)
└── node-sass@2.0.1 (get-stdin@4.0.1, object-assign@2.0.0, replace-ext@0.0.1, nan@1.6.2, semver@4.3.1, shelljs@0.3.0, mkdirp@0.5.0, cross-spawn@0.2.6, chalk@0.5.1, meow@3.0.0, gaze@0.5.1, mocha@2.1.0, npmconf@2.1.1, request@2.53.0)
```

It works fine:)

**Comment by ianqueue** [comment]
@joe5yellow - I upgraded sass-loader globally, but this still doesn't fix my issue, when I try and run the generator again it's still looking for node-sass 1.2.3 which i'm on 2.0.1...

npm WARN prefer global jshint@2.6.3 should be installed with -g
\
> node-sass@1.2.3 install /Users/ianquattlebaum/dev/react/node_modules/sass-loader/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/ianquattlebaum/dev/react/node_modules/sass-loader/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/ianquattlebaum/dev/react/node_modules/sass-loader/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ianquattlebaum/dev/react/node_modules/sass-loader/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass

**Comment by ianqueue** [comment]
I'm also on Node 0.12.0, not sure if that is problem

**Comment by ianqueue** [comment]
Also, trying to pull this from NPM doesn't seem to give me the latest code, perhaps needs to be registered?  Was seeing the missing commas fixed in the latest commit 4 days ago

**Comment by joe5yellow** [comment]
@ianqueue I didn't upgrade sass-loader globally, I just run `npm remove sass-loader --save; npm install sass-loader@0.4.0 --save` in the project folder. It's 9 days since I have been busy offline, hope you made it already :smiley:
