### ISSUE TITLE
Slow React Tests

### ISSUE THREAD

**Issue by renanvalentin** [newtriks/generator-react-webpack#69]
Hey guys, are you with this problem too? A single test is taking more than 3 seconds to complete.

**Comment by newtriks** [comment]
I am currently reviewing testing and should hopefully have some optimisations soon...

**Comment by ColCh** [comment]
*karma-webpack* and *karma* itself are pretty slow and you can't do anything with that.

For my private project, I've replaced *karma-webpack* and *karma* with *mocha* and hacked *jsdom* into tests - thankfully, *React* works nice inside of *jsdom* environment. Tests became pretty fast now!

But, this setup is *hacky*. I don't found a way to inject *jsdom* inside of *mocha* test via `--require` *mocha*'s flag, so ..., every test has header like `require('inject-jsdom.js')`

**Comment by weblogixx** [comment]
I also think that it would be a good idea to make the unit test framework a bit more "pluggable", maybe configurable when setting up new projects?

**Comment by apellizzn** [comment]
+1

**Comment by weblogixx** [comment]
With the current react release, it is possible to run tests faster by using shallow rendering (@see http://simonsmith.io/unit-testing-react-components-without-a-dom/). This goes without using jsdom.

I will try to find out if this is a suitable change for the generator and provide a feature branch for it soon.
Would be nice if we could have fast tests :).

**Comment by renanvalentin** [comment]
Hey guys,

Using this settings for karma make the tests pretty fast:
https://github.com/webpack/karma-webpack#alternative-usage

Thanks!
