### ISSUE TITLE
Update to React 0.13

### ISSUE THREAD

**Issue by marr** [newtriks/generator-react-webpack#73]

**Comment by cancan101** [comment]
Any updates on this?

**Comment by haf** [comment]
+1

**Comment by weblogixx** [comment]
@cancan101: I just added a pull request at https://github.com/newtriks/generator-react-webpack/pull/115 for updated react and react.router packages. Seems to work well for me.

**Comment by weblogixx** [comment]
Update is available since a couple of releases. Closing this issue.
