### ISSUE TITLE
Question: /src/scripts/main.js in gitignore

### ISSUE THREAD

**Issue by frostney** [newtriks/generator-react-webpack#76]
More of a question than an actual issue: Why is there `/src/scripts/main.js` in the last line of the `.gitignore` for the generated app? I'm not seeing that this is file being generated or otherwise available.

**Comment by newtriks** [comment]
@frostney that file is generated by webpack compiling the JS, etc https://github.com/newtriks/generator-react-webpack/blob/master/templates/common/_webpack.config.js#L13
