### ISSUE TITLE
Module not found : ReactProjectApp instead of a the application name + "App"

### ISSUE THREAD

**Issue by remimarenco** [newtriks/generator-react-webpack#80]
Hi!

I just got this generator, and the ```grunt serve``` command does output an error :

```ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/scripts/components/ReactTestApp.js in /home/remi/Dev/reactProject```

BUT, in the js file in "/src/scripts/components/" was "ReactProjectApp", so I renamed it to "ReactTestApp" as my project name is reactTest and everything is fine now!

Maybe a "React" name conflict of something of this kind?

**Comment by dbertella** [comment]
I just had the same exactly issue and renamed my file. Everything seems working now
