### ISSUE TITLE
React.findDOMNode is undefined

### ISSUE THREAD

**Issue by vishnutk** [newtriks/generator-react-webpack#81]
I was going through react docs and using react-webpack generator. While trying findDOMNode method, I found that React object is not having this method and thus console was showing 'undefined' error.

I tried the same with plain react application(http://jsfiddle.net/vishnudas_tekale/vv6vofaw/) and this method is available there.

'use strict';

var React = require('react/addons');
var ReactTransitionGroup = React.addons.TransitionGroup;

// CSS
require('../../styles/normalize.css');

var ReactWebpackDemoApp = React.createClass({
    getInitialState: function() {
      return {userInput: ''};
    },
    handleChange: function(e) {
      this.setState({userInput: e.target.value});
    },
    clearAndFocusInput: function() {
      // Clear the input
      this.setState({userInput: ''}, function() {
        // This code executes after the component is re-rendered
        React.findDOMNode(this.refs.theInput).focus();   // This gives an undefined error
      });
    },
    render: function() {
      return (
        <div>
          <div onClick={this.clearAndFocusInput}>
            Click to Focus and Reset
          </div>
          <input
            ref="theInput"
            value={this.state.userInput}
            onChange={this.handleChange}
          />
        </div>
      );
    }
  });

module.exports = ReactWebpackDemoApp;

 // Reference http://facebook.github.io/react/docs/more-about-refs.html#completing-the-example

**Comment by jnwelzel** [comment]
If you want to get an element from the DOM you should use [refs](https://facebook.github.io/react/docs/more-about-refs.html). This way inside your React component you can do 
```javascript 
var inputEl = this.refs.myInput.getDOMNode().focus();
```

**Comment by vishnutk** [comment]
Yep. Thanks. 

Thats another way of doing it. Ideally when react doc suggesting "findDOMNode" method, should it not be available here?

**Comment by ameyms** [comment]
generator-react-webpack uses React 0.12. `React.findDOMNode` was [introduced](http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html#new-features) in 0.13

**Comment by newtriks** [comment]
This will be addressed once #73 is completed so I will close this issue.
