### ISSUE TITLE
adding fuller version of a component with a flag, and alias

### ISSUE THREAD

**Issue by yonatanmn** [newtriks/generator-react-webpack#84]
I'm thinking of adding an optional flag when using component generator, something like `--full`, that will boilerplate the most used react stages etc, that I find myself tediously writing every time.
This is even more useful when using Reflux (btw, just added a pull request with Reflux support)

It should be something like this:
````
'use strict';

var React = require('react/addons');
//if (architecture=== 'reflux')   
  var Reflux = require('reflux');
  //var Actions = require('actions/...');

//if (stylesLanguage === 'sass')   
 require('styles/componentName.sass');

var  componentName = React.createClass({
//if (architecture=== 'reflux')   
    mixins: [Reflux.ListenerMixin],

  getInitialState: function () {
        return {   };
   },

  componentDidMount: function () {
  },

  render: function () {
    return (
        <div>
          <p>Content for componentName </p>
        </div>
      );
  }
});
````

**discussion**
1. I use `getInitialState` and `componentDidMount`, and reflux stuff all the time, what's yours boiler-plated code?
2. what will be a proper name for this option (e.g `--full`)
3. I think `react-webpack:component` is quite a lot of text. We can [create an alias](https://github.com/yeoman/generator/issues/663). like `react-webpack:cmp` or `react-webpack:c` - what do you think will be suitable? (and what about `react-webpack:action` and `react-webpack:store`?)

**Comment by weblogixx** [comment]
Seems to be integrated for quite a time. Closing this.
