### ISSUE TITLE
renaming the project

### ISSUE THREAD

**Issue by yonatanmn** [newtriks/generator-react-webpack#85]
For every operation, one needs to write `yo react-webpack`, quite long I assume. 
There is [no workaround](
https://github.com/yeoman/generator/issues/788) for alias name, so the only option is to rename the entire project.

`generator-react` is already taken. Can anyone think about a cool and short name?

**Comment by ColCh** [comment]
You can use your shell feature named **alias**

I wrote small example for you:  
```sh
export yorw="yo react-webpack"
```
 
You can make this permanent with adding that line to your **~/.bashrc**.

**Comment by newtriks** [comment]
That's the exact route I was thinking after realising this was out of scope for yeoman  👍 thanks Max


On Saturday, 11 Apr 2015 at 16:45, Max Sysoev <notifications@github.com>, wrote:

You can use your shell feature named alias


I wrote small example for you:  


export yorw="yo react-webpack"


You can make this permanent with adding that line to your ~/.bashrc.

**Comment by yonatanmn** [comment]
I disagree with this solution.
First, bash is a unix thing, not everyone uses it. 
Second, this is a hack, not a normal way. the all point of yeoman is make life shorter, and this long name might prevent potential users from using this generator. 
lastly - webpack is one feature of this generator, but not its main core. I believe this will be the ultimate generator for react, similar to generator-angular, so the name should represent that.

**Comment by semigroupoid** [comment]
Sorry, I disagree with that. Using aliases for abbreviations is not a hack, its one of their main use cases. I don't know if you use Windows (because of your "unix thing" comment) but I bet that the Windows command line tools have some way of defining aliases, too. Abbreviations and such are a very subjective thing, similar to keyboard shortcuts and as such should be handled in your terminal configuration and not by renaming the project. (There is also a zsh plugin that gives you auto-completion of generator names.)
Regarding your last point, I think webpack is an essential part of this project and one that seperates this generator from others. Also, the name generator-react is not much shorter than generator-react-webpack, is it?

**Comment by yonatanmn** [comment]
Iv'e tried with windows, so instead of `react-webpack` i'll do 
`rw` but then you cannot do `rw:component`. any way - this is a hack, in the manner that the point of yeoman generators is to make your life easy and short, without adding anything around . 
Webpack is not an essential part, because the user who uses this generator wants React mainly, and will be glad to have webpack (or browerify or whatever) too, but that's not why he came. 
Currently this generator is the most popular one for react, and should have a sterile name - so it can remain in the top. similar to generator-angular.
and it's not `generator-react` in the console - only `react`, which is less than a half of `react-webpack`.

**Comment by ColCh** [comment]
@yonatanmn sorry I've forgot about subgenerators. Hm.. this is a hard issue...
I'm sure that renaming the project is not a solution.

Ha! What about (npm scopes)[http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages]? With 'em it's possible to place this generator like `@newtricks/generator-react`

**Comment by yonatanmn** [comment]
The problem is with how Yeoman will read this, stating he is only looking for `generator-XXX`, any way if this is the only issue, we can use `generator-react`, since https://github.com/nemophrost/generator-react is not alive, and we can ask the owner to drop it, or alternatively think of a cool and short name

**Comment by semigroupoid** [comment]
Honestly, I still don't see the point. If subgenerators don't work, use ```alias rwc="yo react-webpack:c"``` etc. Again, shell aliases are not a hack. They are primarily used for abbreviations! 
In my opinion, the usage of webpack makes this generator to opinionated for a generic name such as ```generator-react```.

**Comment by yonatanmn** [comment]
In windows, tried : `doskey r:c=yo react-webpack:c`, and then `r:c test`. 
result: 
`Error: Did not provide required argument ←[1mname←[22m!`
I think doskey can't get more code after the alias.

**Comment by semigroupoid** [comment]
I don't have a Windows machine, but did you try ```doskey r:c="yo react-webpack:c"```? You probably have to wrap the actual command in quotes (you also have to do that in bash).

**Comment by yonatanmn** [comment]
the correct way is what i quoted before (that's why it gave 'no name' error). Tried yours just to make sure - not working at all. 
(can you verify `r:c test` works in mac?)

**Comment by semigroupoid** [comment]
Yes ```r:c test``` works. First:

```
alias r:c="yo react-webpack:c"
```
Then you can do:
```
r:c test
   create src/components/Test.js
   create test/spec/components/Test.js
   create src/styles/Test.css
```

**Comment by yonatanmn** [comment]
Ok, but still no windows solution...

**Comment by semigroupoid** [comment]
What about cygwin or PowerShell?

**Comment by yonatanmn** [comment]
I'll check them out.
any way I still in my opinion that the project should be renamed :)
