### ISSUE TITLE
Build static pages with a middleware

### ISSUE THREAD

**Issue by kox** [newtriks/generator-react-webpack#94]
Hi,

I think it would be interesting to have an option to build static pages. It's one of the stronger points of React and great for SEO and, also for have some relevant content in browsers with Javascript disabled.

thanks for all

**Comment by weblogixx** [comment]
This is currently out of scope for the generator as it would imply we needed to build a backend toolchain, too. Maybe this would be a feature for a new generator-react-webpack-backend generator?
