### ISSUE TITLE
directory structure 

### ISSUE THREAD

**Issue by yonatanmn** [newtriks/generator-react-webpack#95]
In one of the recent changes, the structure changed from:
````
-src
    -scripts
        -components
````
to
````
-src
    -components
````

If someone has started a project with earlier version, and then updated it, and now he tries to use the `component` generator, the new comp will be added to the wrong directory. The solution should have a some settings for where to save things. 
Any way, that's not such a big deal. Just wanted to mention the problem

**Comment by newtriks** [comment]
Thanks @yonatanmn, yeh small tweak and maybe a to do in the future....
