### ISSUE TITLE
Duplicative Routes

### ISSUE THREAD

**Issue by cancan101** [newtriks/generator-react-webpack#96]
Why is this written like this:
```jsx
var Routes = (
  <Route handler={<%= scriptAppName %>}>
    <Route name="/" handler={<%= scriptAppName %>}/>
  </Route>
);
```
as opposed to just:
```jsx
var Routes = (
  <Route path="/" handler={<%= scriptAppName %>} />
);
```

**Comment by newtriks** [comment]
Most likely either an approach to an older version of react router, or I simply added a route as an example. I am not sure. If you want to make the change, test and send a pull request I will happily merge.

**Comment by weblogixx** [comment]
I think this was to make nested rules possible and easier to do something like this:

```javascript
var Routes = (
  <Route handler={<%= scriptAppName %>}>
    <Route name="/" handler={<%= scriptAppName %>}/>
    <Route name="/test" handler={TestHandler}/>
  </Route>
);
```
