### ISSUE TITLE
React as Global?

### ISSUE THREAD

**Issue by cancan101** [newtriks/generator-react-webpack#98]
Why is `React` listed as a global [here](https://github.com/newtriks/generator-react-webpack/blob/d73699fbf27a25ed7395f8c7b71dc5f15883262f/templates/common/root/.jshintrc#L24). I assume that it should be imported / required in each file?

**Comment by newtriks** [comment]
This is simply to stop `jshint` complaining about React in the global namespace.

**Comment by cancan101** [comment]
I understand what it does buy why are you expecting React to be in the global namespace?

**Comment by newtriks** [comment]
Good point :P must have crept in at some point for some unknown reason. Happy to accept a pull request if you wanna contribute to the repos based on your questions raised.
