### ISSUE TITLE
Use .jsx file endings for components

### ISSUE THREAD

**Issue by weblogixx** [newtriks/generator-react-webpack#99]
It would be nice if the generator would use the correct file ending for generated components (.*jsx* instead of .js). This would have the benefit that editors (like Atom or Brackets) would be able to guess the file format correclty if they support jsx-syntax.

**Comment by weblogixx** [comment]
Hi @newtriks,

thank you for your fast response. I think in this case it should at least be optional to use the .jsx (defaulting to .js).

When using CI-Tools (like SonarQube or linters like jsHint) files with jsx-syntax are not parseable and will therefore lead to errors that must be fixed in each of those various systems.

**Comment by newtriks** [comment]
@weblogixx good point, as an option would be feasible.
